/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/t0rmund/devel/nim/lib -o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/cairo_cairo.o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/cairo_cairo.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ;
typedef struct tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q;
typedef struct tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ;
typedef struct tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA;
typedef struct tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg;
typedef struct tyObject_TRectangleList_vvpqX6khJnno00rgLEXeuA tyObject_TRectangleList_vvpqX6khJnno00rgLEXeuA;
typedef struct tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g;
typedef struct tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A;
typedef struct tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng;
typedef struct tyObject_TGlyph_cQi4iCE8fMipmwK9b6kCuIA tyObject_TGlyph_cQi4iCE8fMipmwK9b6kCuIA;
typedef struct tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw;
typedef struct tyObject_TFontExtents_hTANf9ahgxUI9bdG8vHBckaA tyObject_TFontExtents_hTANf9ahgxUI9bdG8vHBckaA;
typedef struct tyObject_TPath_vnkuCCxOl1cWx2vFchn6Uw tyObject_TPath_vnkuCCxOl1cWx2vFchn6Uw;
typedef struct tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA;
typedef struct tyObject_TRectangle_B2aOO7bSuYVjjirpymXCnw tyObject_TRectangle_B2aOO7bSuYVjjirpymXCnw;
typedef struct tyObject_TPathData_Vl5Vb9c3ONTXdab6wHjf6oA tyObject_TPathData_Vl5Vb9c3ONTXdab6wHjf6oA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, tyProc_07QdujGjOf8s9cNEpM0S9aKQ) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ*, tyProc_bTW7Hl6B8eRPusBByIUiKg) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* target);
typedef N_CDECL_PTR(tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ*, tyProc_RNX29bk9aCAILf0cldsQQigA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(void, tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(NI32, tyProc_003eudyNUy9c9c9bINdjNuXWQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(void*, tyProc_25YgodgyVmLA8488tNz4KQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key);
typedef NU8 tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg;
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* data);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_8SKnWuTMsmqaYOdEMDugaA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key, void* user_data, tyProc_32w2ZypAyMWuajvi2Jt79cg destroy);
typedef NU16 tyEnum_TContent_XWCTShEWOXrQmqtmqaQClg;
typedef N_CDECL_PTR(void, tyProc_QFcosXU7VIBNlSp9c7ZlXVQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyEnum_TContent_XWCTShEWOXrQmqtmqaQClg content);
typedef N_CDECL_PTR(tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA*, tyProc_yaV5mg4oeGskSsNHTsPaBA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef NU8 tyEnum_TOperator_lJYoDV2E7V1wO8lr29aTb2g;
typedef N_CDECL_PTR(void, tyProc_xjXqSV7Q1FpO9cHdSpTYefw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyEnum_TOperator_lJYoDV2E7V1wO8lr29aTb2g op);
typedef N_CDECL_PTR(void, tyProc_v9bnMVZC9cjFuZKli9a20Vqqw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* source);
typedef N_CDECL_PTR(void, tyProc_Vig9bMGAwzJYDfhF79cygw0Q) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF red, NF green, NF blue);
typedef N_CDECL_PTR(void, tyProc_WFLTHAe29bld14aJj9beCK5A) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF red, NF green, NF blue, NF alpha);
typedef N_CDECL_PTR(void, tyProc_F5LkdYXGj3yMMWLNUL9cLOA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, NF x, NF y);
typedef N_CDECL_PTR(void, tyProc_IDk3KxgJRpZTfHk6zjVF9cg) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF tolerance);
typedef NU8 tyEnum_TAntialias_xvU9blx7edZaDkNOvyxoQmA;
typedef N_CDECL_PTR(void, tyProc_VnOGDxkHZlQKTEdg9bzDacA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyEnum_TAntialias_xvU9blx7edZaDkNOvyxoQmA antialias);
typedef NU8 tyEnum_TFillRule_Juk1RxdVCOhUcB4L8FxYew;
typedef N_CDECL_PTR(void, tyProc_GKgVMGIR9bcSVTrGVlKCZUw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyEnum_TFillRule_Juk1RxdVCOhUcB4L8FxYew fill_rule);
typedef NU8 tyEnum_TLineCap_K8tdwfisrzblmEa8VxlM9aQ;
typedef N_CDECL_PTR(void, tyProc_iejs3M9bTicev3z3gzifcvg) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyEnum_TLineCap_K8tdwfisrzblmEa8VxlM9aQ line_cap);
typedef NU8 tyEnum_TLineJoin_B4vZMdZcUIB9coIRmGAcWeQ;
typedef N_CDECL_PTR(void, tyProc_VZZ8sQYIoEgFODl5stMqOQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyEnum_TLineJoin_B4vZMdZcUIB9coIRmGAcWeQ line_join);
typedef N_CDECL_PTR(void, tyProc_lECD39bCmUBecTcvA0sUMNA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF* dashes, NI dashesLen_0, NF offset);
typedef N_CDECL_PTR(void, tyProc_8F2XGMxl7hq1cDz14pJs8w) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF tx, NF ty);
typedef N_CDECL_PTR(void, tyProc_K5FECQ0ybPb9atWPSnIi3VA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix);
typedef N_CDECL_PTR(void, tyProc_G1IzaTjB3nLZSlmIGBQ23Q) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF* x, NF* y);
typedef N_CDECL_PTR(void, tyProc_17SydyDYqHdll9c39brh1Oyg) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF x1, NF y1, NF x2, NF y2, NF x3, NF y3);
typedef N_CDECL_PTR(void, tyProc_YMaQGOsqXjPV1HbRPnFGrg) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF xc, NF yc, NF radius, NF angle1, NF angle2);
typedef N_CDECL_PTR(NI32, tyProc_t5KjWrxjUu40ao8Tp0V7XQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF x, NF y);
typedef N_CDECL_PTR(void, tyProc_339btklVCd1SL8BqHamG2Sw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NF* x1, NF* y1, NF* x2, NF* y2);
typedef N_CDECL_PTR(tyObject_TRectangleList_vvpqX6khJnno00rgLEXeuA*, tyProc_9aukviZdgv7BLiI3X9artC4Q) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(void, tyProc_4babc4K0ehjpA6BgPlEevw) (tyObject_TRectangleList_vvpqX6khJnno00rgLEXeuA* rectangle_list);
typedef N_CDECL_PTR(tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g*, tyProc_33NIE6G8GLZ7XfoluRBl6g) (void);
typedef N_CDECL_PTR(tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g*, tyProc_VHjFICAr2J3eeACpQrvlug) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* original);
typedef N_CDECL_PTR(void, tyProc_ScjVnXD428Cge0AhV0NjYA) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_Lrd35sSswkqWXPt2LTy36g) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(void, tyProc_Mj5Jc7sZKtFxS9cLqfyVaOA) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options, tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* other);
typedef N_CDECL_PTR(NI32, tyProc_CMwYVC7RjtSkJEY3ALD8zA) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options, tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* other);
typedef N_CDECL_PTR(NI32, tyProc_ia27lCtds76qrQFLt6D1NQ) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(void, tyProc_9cAjRmXyG1GE3wa7ESpjJ9bg) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options, tyEnum_TAntialias_xvU9blx7edZaDkNOvyxoQmA antialias);
typedef N_CDECL_PTR(tyEnum_TAntialias_xvU9blx7edZaDkNOvyxoQmA, tyProc_c9aWrPCbHK9azFxHs9bMRgkeg) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef NU8 tyEnum_TSubpixelOrder_llWgnOvR4QNZNqBYSh46gA;
typedef N_CDECL_PTR(void, tyProc_UXkckW9c5APvAZQCpiWtwaw) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options, tyEnum_TSubpixelOrder_llWgnOvR4QNZNqBYSh46gA subpixel_order);
typedef N_CDECL_PTR(tyEnum_TSubpixelOrder_llWgnOvR4QNZNqBYSh46gA, tyProc_Dy1F1Ti11YFnGBlcZukFxg) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef NU8 tyEnum_THintStyle_ybXatSJgEOWNAfYkqhjbTA;
typedef N_CDECL_PTR(void, tyProc_9ajjrZ0cSz2C9anXqhwL6HEw) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options, tyEnum_THintStyle_ybXatSJgEOWNAfYkqhjbTA hint_style);
typedef N_CDECL_PTR(tyEnum_THintStyle_ybXatSJgEOWNAfYkqhjbTA, tyProc_uJWiMek9bz5a69cNCEbZoujw) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef NU8 tyEnum_THintMetrics_6HC9bqPEnTH9cHUpbw5meZTg;
typedef N_CDECL_PTR(void, tyProc_OJCP0679acdt5iiebX7nOtg) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options, tyEnum_THintMetrics_6HC9bqPEnTH9cHUpbw5meZTg hint_metrics);
typedef N_CDECL_PTR(tyEnum_THintMetrics_6HC9bqPEnTH9cHUpbw5meZTg, tyProc_ebhlAmxi6jQgAd0nXFRyvw) (tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef NU8 tyEnum_TFontSlant_7MIiOcVK9cJnNzW5hRpiIsA;
typedef NU8 tyEnum_TFontWeight_O2KvtrBlcIPNNa7omI1BDw;
typedef N_CDECL_PTR(void, tyProc_fCq4b3nVFmfVbpQ9btjjtbw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NCSTRING family, tyEnum_TFontSlant_7MIiOcVK9cJnNzW5hRpiIsA slant, tyEnum_TFontWeight_O2KvtrBlcIPNNa7omI1BDw weight);
typedef N_CDECL_PTR(void, tyProc_YdesHI3MYrrRR08Jh7zhgQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(void, tyProc_47gYkL8UstHcH6pjkvyRuQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face);
typedef N_CDECL_PTR(tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A*, tyProc_g9aqNx09cgnUoR7hwH6IZDKQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(void, tyProc_XdYFq9ck4QNcB9cvooxUk1uw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng*, tyProc_nvcYXs1W2nD7FDtfIBQZ9cw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(void, tyProc_a7UrMyL3x4LGrBOzeGOoMQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NCSTRING utf8);
typedef N_CDECL_PTR(void, tyProc_i9aN6X7KBEoLzyWf8K5DEMg) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TGlyph_cQi4iCE8fMipmwK9b6kCuIA* glyphs, NI32 num_glyphs);
typedef N_CDECL_PTR(void, tyProc_CDvsVbFfhFwoVQCQF4otIQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, NCSTRING utf8, tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw* extents);
typedef N_CDECL_PTR(void, tyProc_bdoONiSmawyiu4BI2cS38A) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TGlyph_cQi4iCE8fMipmwK9b6kCuIA* glyphs, NI32 num_glyphs, tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw* extents);
typedef N_CDECL_PTR(void, tyProc_8a9aZys9anbr86hSlxaItX7w) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TFontExtents_hTANf9ahgxUI9bdG8vHBckaA* extents);
typedef N_CDECL_PTR(tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A*, tyProc_nDJK9aApXAKWYhxqqFWnVeA) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face);
typedef N_CDECL_PTR(void, tyProc_VWydpHmLvuDbDADfqZVm9cQ) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face);
typedef N_CDECL_PTR(NI32, tyProc_21dF9c72K6fJRyJ6KsNm1qA) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_EGsm7wlcs9b0t5cKg3R9blrw) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face);
typedef NU8 tyEnum_TFontType_trXkrcne28XylIM19cOOEjA;
typedef N_CDECL_PTR(tyEnum_TFontType_trXkrcne28XylIM19cOOEjA, tyProc_S4bSrr6sfz9abNf9b5NnYvIQ) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face);
typedef N_CDECL_PTR(void*, tyProc_qp0e6egyR7TRFBvIMUN2zQ) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_OgAVtuI1sds9aPS4feUpKKw) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key, void* user_data, tyProc_32w2ZypAyMWuajvi2Jt79cg destroy);
typedef N_CDECL_PTR(tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng*, tyProc_IaGyO0L5qZlmbYIaRkXYnw) (tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A* font_face, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* font_matrix, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* ctm, tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng*, tyProc_oqmnKiueAPhIfG5GiIVqpA) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(void, tyProc_rRipFnLK2R9a8uFeVDgP9ahA) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(NI32, tyProc_fC9a52vQNeTujfvy39b1ClCA) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_C13HO6TYqLvda9b5bRGbrhQ) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(tyEnum_TFontType_trXkrcne28XylIM19cOOEjA, tyProc_9a6dQR84cnfZqWhvdW9brv6A) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(void*, tyProc_UVuZMKiSo0MVveS5Wxh9b3A) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_DjQFt0MiXawYyjjT9bWr9cZw) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key, void* user_data, tyProc_32w2ZypAyMWuajvi2Jt79cg destroy);
typedef N_CDECL_PTR(void, tyProc_QS4pIWzJA9bO3FDTc9c5WNQQ) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, tyObject_TFontExtents_hTANf9ahgxUI9bdG8vHBckaA* extents);
typedef N_CDECL_PTR(void, tyProc_4NgXtH9atUOaCa9ca6ipUvSg) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, NCSTRING utf8, tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw* extents);
typedef N_CDECL_PTR(void, tyProc_5TuLcEoM6ARbOzfnsxfDcA) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, tyObject_TGlyph_cQi4iCE8fMipmwK9b6kCuIA* glyphs, NI32 num_glyphs, tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw* extents);
typedef N_CDECL_PTR(tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A*, tyProc_Cylj9avAuP0mvXv8Z9aqGXDQ) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font);
typedef N_CDECL_PTR(void, tyProc_n1oDjTjHOH39cY9at4g7AuDw) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* font_matrix);
typedef N_CDECL_PTR(void, tyProc_WlUK9aMj542mYOAb9bmJm7Jg) (tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng* scaled_font, tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(tyEnum_TOperator_lJYoDV2E7V1wO8lr29aTb2g, tyProc_7UgOQ2tsMSiCQMF0TLNXAQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(NF, tyProc_28zonchclHPmWSReHMwVyQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(tyEnum_TAntialias_xvU9blx7edZaDkNOvyxoQmA, tyProc_832GEpEK0JdEsAX1LFgWYw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(tyEnum_TFillRule_Juk1RxdVCOhUcB4L8FxYew, tyProc_6GAifTsaPCNyhtO6XTb2FA) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(tyEnum_TLineCap_K8tdwfisrzblmEa8VxlM9aQ, tyProc_0gnDlYjBsggHJRI1EXo57g) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(tyEnum_TLineJoin_B4vZMdZcUIB9coIRmGAcWeQ, tyProc_xmiaqgCIdhsWTdlQKgwNGQ) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_lo9aTFzzb9ctKr2AU61zDU6w) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(tyObject_TPath_vnkuCCxOl1cWx2vFchn6Uw*, tyProc_XeQF9bhOr2MD430IokV9cv8A) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(void, tyProc_AXsKTk2AT34S84BOY0kX8A) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr, tyObject_TPath_vnkuCCxOl1cWx2vFchn6Uw* path);
typedef N_CDECL_PTR(void, tyProc_Phx1pnFtRjsF0U37Ztn1kA) (tyObject_TPath_vnkuCCxOl1cWx2vFchn6Uw* path);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_mR44TxkOMM9bNebf0XQCi9cw) (tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ* cr);
typedef N_CDECL_PTR(NCSTRING, tyProc_r5WpYAfpxEqrcCiGpWLHXQ) (tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg status);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_XehrqkX6mJFP8d09b43s3fg) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* other, tyEnum_TContent_XWCTShEWOXrQmqtmqaQClg content, NI32 width, NI32 height);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_c78ufLOvL9cbxy6S4zFU6zQ) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(void, tyProc_MSMGzSUseJ60axIE1SMYvw) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(NI32, tyProc_iAzWoI5ZgPU10dxrHCTufA) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_mAFv9brcf06NIf9aBHn0n9coA) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef NU8 tyEnum_TSurfaceType_a7zbWnbG2LYzinpQbpPlaQ;
typedef N_CDECL_PTR(tyEnum_TSurfaceType_a7zbWnbG2LYzinpQbpPlaQ, tyProc_PRzMR7K9b7Vlzxfu4uAh4oA) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(tyEnum_TContent_XWCTShEWOXrQmqtmqaQClg, tyProc_GUY0uaMj5S6KSj14MSmESw) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_wiBE3rmX3joDIm1hE5o6Bg) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, NCSTRING filename);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_5gD6KLCG9bDME9aSXZp3YkxQ) (void* closure, NCSTRING data, NI32 len);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_hY9aJzK0lzZPab0BYxLz6aQ) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, tyProc_5gD6KLCG9bDME9aSXZp3YkxQ write_func, void* closure);
typedef N_CDECL_PTR(void*, tyProc_6KsatHUTy686VVpnNJFqsg) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_ZoXFGrEmg3eJyqsmCbtYpg) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key, void* user_data, tyProc_32w2ZypAyMWuajvi2Jt79cg destroy);
typedef N_CDECL_PTR(void, tyProc_5s9bXD22uREj8Idfn4E33XQ) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g* options);
typedef N_CDECL_PTR(void, tyProc_9b4RHlxg89b1yB4rnlhtxLQQ) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, NI32 x, NI32 y, NI32 width, NI32 height);
typedef N_CDECL_PTR(void, tyProc_ysQ8zhM82MX3e6sS4SpH4w) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, NF x_offset, NF y_offset);
typedef N_CDECL_PTR(void, tyProc_9aatS6b0zXqkNGXFLvpleDA) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, NF* x_offset, NF* y_offset);
typedef NU8 tyEnum_TFormat_nwbJqvB9aCMNUaRkqbZA8fg;
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_gBjtZoPOtjvOF4yccS4V7Q) (tyEnum_TFormat_nwbJqvB9aCMNUaRkqbZA8fg format, NI32 width, NI32 height);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_Uoita1I61h1gE7KHOrDawA) (NCSTRING data, tyEnum_TFormat_nwbJqvB9aCMNUaRkqbZA8fg format, NI32 width, NI32 height, NI32 stride);
typedef N_CDECL_PTR(NCSTRING, tyProc_hfgEFCmitG5OIl8OtxQGlw) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(tyEnum_TFormat_nwbJqvB9aCMNUaRkqbZA8fg, tyProc_fM0MZsmwSRd2ie6RtsZTPg) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_hgZhJ8Q75gQUb9aku7HTKRA) (NCSTRING filename);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_lFTTSaN5PhB0wXCiGfKZOw) (tyProc_5gD6KLCG9bDME9aSXZp3YkxQ read_func, void* closure);
typedef N_CDECL_PTR(tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA*, tyProc_609a5FRdyzdkmQD49b5pZjtQ) (NF red, NF green, NF blue);
typedef N_CDECL_PTR(tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA*, tyProc_h9cpVNoNS9azUSdi23h4WrJA) (NF red, NF green, NF blue, NF alpha);
typedef N_CDECL_PTR(tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA*, tyProc_A39bwfAAhDNLh0wNH3v0GTw) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface);
typedef N_CDECL_PTR(tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA*, tyProc_acSgkkZ5DDKO5QEU6ZLIKg) (NF cx0, NF cy0, NF radius0, NF cx1, NF cy1, NF radius1);
typedef N_CDECL_PTR(tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA*, tyProc_wxC0L9cSbhFTW1O9cv9bSIOOQ) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef N_CDECL_PTR(void, tyProc_fOn9bZgC2cIRrps71OVzqDw) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef N_CDECL_PTR(NI32, tyProc_cjsfU9cNwS9aOVNpUSTZDdRg) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_FUmpeEGlnmZIz4xTHDbNjw) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef N_CDECL_PTR(void*, tyProc_s9a9aABS1CxWyZ9aL9bKBjN4sQ) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_pU9aF9a4LSX5Lq8he8uApwZA) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ* key, void* user_data, tyProc_32w2ZypAyMWuajvi2Jt79cg destroy);
typedef NU8 tyEnum_TPatternType_W6zoIyqZkcwORqnumJD7lg;
typedef N_CDECL_PTR(tyEnum_TPatternType_W6zoIyqZkcwORqnumJD7lg, tyProc_Aeb0lLI2E9bXlFuIc7Ot9c4g) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef N_CDECL_PTR(void, tyProc_wAJSvEMQR3dsEE9adeaNR5g) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, NF offset, NF red, NF green, NF blue);
typedef N_CDECL_PTR(void, tyProc_Z9c2Gh9bseNrq80paeWhiLvw) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, NF offset, NF red, NF green, NF blue, NF alpha);
typedef N_CDECL_PTR(void, tyProc_na25J7cDhfHBnapdWR20ng) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix);
typedef NU8 tyEnum_TExtend_xlh9b2HdrOO6v5bhCkFg13Q;
typedef N_CDECL_PTR(void, tyProc_b0cvLkOO6mAfu9cUHkAcH7A) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, tyEnum_TExtend_xlh9b2HdrOO6v5bhCkFg13Q extend);
typedef N_CDECL_PTR(tyEnum_TExtend_xlh9b2HdrOO6v5bhCkFg13Q, tyProc_zL9bBsNSEjNx9anZGaPZNY3A) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef NU8 tyEnum_TFilter_kL37ie2iwltln2IARvjh9cA;
typedef N_CDECL_PTR(void, tyProc_KVWFtQxhyUqXCiNqJB0XdQ) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, tyEnum_TFilter_kL37ie2iwltln2IARvjh9cA filter);
typedef N_CDECL_PTR(tyEnum_TFilter_kL37ie2iwltln2IARvjh9cA, tyProc_XJlMpSjcdRQ9cv1NS06k6wg) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_4VXoJS9czZ8R5T9ascqzsAKA) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, NF* red, NF* green, NF* blue, NF* alpha);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_Ut1VYiCzyx4CmVjkGAA9aHw) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q** surface);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_FmaS3degI3AzWSb7zwDGEg) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, NI32 index, NF* offset, NF* red, NF* green, NF* blue, NF* alpha);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_W8tksr9aQ8bLKbdGATtOVZQ) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, NI32* count);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_ncWD0dq9aoi3dz9aE2rjdkcw) (tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA* pattern, NF* x0, NF* y0, NF* r0, NF* x1, NF* y1, NF* r1);
typedef N_CDECL_PTR(void, tyProc_jCeHA0YLZ77AF1guqUdGLg) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix, NF xx, NF yx, NF xy, NF yy, NF x0, NF y0);
typedef N_CDECL_PTR(void, tyProc_zzhElsnicQsyaaf9ciyveLw) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix);
typedef N_CDECL_PTR(void, tyProc_0W09cnQPtlS5pZclissM9aPQ) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix, NF tx, NF ty);
typedef N_CDECL_PTR(void, tyProc_V6TgiyXVtkiiGQ0z9cZmJBA) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix, NF radians);
typedef N_CDECL_PTR(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg, tyProc_gek9a89c05JDZDAKWud8hTpw) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix);
typedef N_CDECL_PTR(void, tyProc_HAFfIEfyf52E83kbhIan9aQ) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* result, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* a, tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* b);
typedef N_CDECL_PTR(void, tyProc_9cE0bBdbiT2zqc06U3dLL8g) (tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg* matrix, NF* dx, NF* dy);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_oXjJdMsROOz7shLxEUuTFg) (NCSTRING filename, NF width_in_points, NF height_in_points);
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_oPRl5xAHmhnhJRzAAN20nQ) (tyProc_5gD6KLCG9bDME9aSXZp3YkxQ write_func, void* closure, NF width_in_points, NF height_in_points);
typedef N_CDECL_PTR(void, tyProc_6mY1HXnIEx4tYTeCD0J3VQ) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, NCSTRING comment);
typedef NU8 tyEnum_TSvgVersion_SoYxYkFo4kx4KVmy6jLDMg;
typedef N_CDECL_PTR(void, tyProc_td5ALJgXfT4IynJRSfZ0Ww) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* surface, tyEnum_TSvgVersion_SoYxYkFo4kx4KVmy6jLDMg version);
typedef N_CDECL_PTR(NCSTRING, tyProc_e19a0rq9babSEwP7Rdc9bfPRA) (tyEnum_TSvgVersion_SoYxYkFo4kx4KVmy6jLDMg version);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA {
  Exception Sup;
};
typedef N_CDECL_PTR(tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q*, tyProc_wE1dpGGgx7v5XgHCN8T0cQ) (tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q* target, double x, double y, double w, double h);
struct tyObject_TContext_DqEg9aCItmMsvwBgN4gLqOQ {
char dummy;
};
struct tyObject_TSurface_130VEGFhvSUqvKj5T6vP1Q {
char dummy;
};
struct tyObject_TUserDataKey_k5pHpdWsQlAmghQ4mTFFtQ {
NI32 unused;
};
struct tyObject_TPattern_GW8SfkkB4j0z9cQrQkftu9aA {
char dummy;
};
struct tyObject_TMatrix_qbQTLIGuIX5urASX29aE9atg {
NF xx;
NF yx;
NF xy;
NF yy;
NF x0;
NF y0;
};
struct tyObject_TRectangleList_vvpqX6khJnno00rgLEXeuA {
tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg status;
tyObject_TRectangle_B2aOO7bSuYVjjirpymXCnw* rectangles;
NI32 num_rectangles;
};
struct tyObject_TFontOptions_SVvdFfKII9bdrJ9c9bgTFzM0g {
char dummy;
};
struct tyObject_TFontFace_3x0VREYgNg9cwbTRjbK5q4A {
char dummy;
};
struct tyObject_TScaledFont_irJ0Aq2v6vjMirwnqRQsng {
char dummy;
};
struct tyObject_TGlyph_cQi4iCE8fMipmwK9b6kCuIA {
NI32 index;
NF x;
NF y;
};
struct tyObject_TTextExtents_xPHxa002PPUWFTiM8P5FUw {
NF x_bearing;
NF y_bearing;
NF width;
NF height;
NF x_advance;
NF y_advance;
};
struct tyObject_TFontExtents_hTANf9ahgxUI9bdG8vHBckaA {
NF ascent;
NF descent;
NF height;
NF max_x_advance;
NF max_y_advance;
};
struct tyObject_TPath_vnkuCCxOl1cWx2vFchn6Uw {
tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg status;
tyObject_TPathData_Vl5Vb9c3ONTXdab6wHjf6oA* data;
NI32 num_data;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_TRectangle_B2aOO7bSuYVjjirpymXCnw {
NF x;
NF y;
NF width;
NF height;
};
struct tyObject_TPathData_Vl5Vb9c3ONTXdab6wHjf6oA {
NF x;
NF y;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(void, version_NrV9b65DuwYQFfiBz19aMlZg)(NI32* major, NI32* minor, NI32* micro);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, checkStatus_2qpdTRrt4eXupJE86zN2hA)(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg s);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static void* TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2;
tyProc_07QdujGjOf8s9cNEpM0S9aKQ Dl_124728_;
tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_124730_;
tyProc_bTW7Hl6B8eRPusBByIUiKg Dl_124738_;
tyProc_RNX29bk9aCAILf0cldsQQigA Dl_124741_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124744_;
tyProc_003eudyNUy9c9c9bINdjNuXWQ Dl_124747_;
tyProc_25YgodgyVmLA8488tNz4KQ Dl_124750_;
tyProc_8SKnWuTMsmqaYOdEMDugaA Dl_124754_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124760_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124763_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124766_;
tyProc_QFcosXU7VIBNlSp9c7ZlXVQ Dl_124769_;
tyProc_yaV5mg4oeGskSsNHTsPaBA Dl_124773_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124776_;
tyProc_xjXqSV7Q1FpO9cHdSpTYefw Dl_124779_;
tyProc_v9bnMVZC9cjFuZKli9a20Vqqw Dl_124783_;
tyProc_Vig9bMGAwzJYDfhF79cygw0Q Dl_124787_;
tyProc_WFLTHAe29bld14aJj9beCK5A Dl_124793_;
tyProc_F5LkdYXGj3yMMWLNUL9cLOA Dl_124800_;
tyProc_IDk3KxgJRpZTfHk6zjVF9cg Dl_124806_;
tyProc_VnOGDxkHZlQKTEdg9bzDacA Dl_124810_;
tyProc_GKgVMGIR9bcSVTrGVlKCZUw Dl_124814_;
tyProc_IDk3KxgJRpZTfHk6zjVF9cg Dl_124818_;
tyProc_iejs3M9bTicev3z3gzifcvg Dl_124822_;
tyProc_VZZ8sQYIoEgFODl5stMqOQ Dl_124826_;
tyProc_lECD39bCmUBecTcvA0sUMNA Dl_124830_;
tyProc_IDk3KxgJRpZTfHk6zjVF9cg Dl_124836_;
tyProc_8F2XGMxl7hq1cDz14pJs8w Dl_124840_;
tyProc_8F2XGMxl7hq1cDz14pJs8w Dl_124845_;
tyProc_IDk3KxgJRpZTfHk6zjVF9cg Dl_124850_;
tyProc_K5FECQ0ybPb9atWPSnIi3VA Dl_124854_;
tyProc_K5FECQ0ybPb9atWPSnIi3VA Dl_124858_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124862_;
tyProc_G1IzaTjB3nLZSlmIGBQ23Q Dl_124865_;
tyProc_G1IzaTjB3nLZSlmIGBQ23Q Dl_124871_;
tyProc_G1IzaTjB3nLZSlmIGBQ23Q Dl_124877_;
tyProc_G1IzaTjB3nLZSlmIGBQ23Q Dl_124883_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124889_;
tyProc_8F2XGMxl7hq1cDz14pJs8w Dl_124892_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124897_;
tyProc_8F2XGMxl7hq1cDz14pJs8w Dl_124900_;
tyProc_17SydyDYqHdll9c39brh1Oyg Dl_124905_;
tyProc_YMaQGOsqXjPV1HbRPnFGrg Dl_124914_;
tyProc_YMaQGOsqXjPV1HbRPnFGrg Dl_124922_;
tyProc_8F2XGMxl7hq1cDz14pJs8w Dl_124930_;
tyProc_8F2XGMxl7hq1cDz14pJs8w Dl_124935_;
tyProc_17SydyDYqHdll9c39brh1Oyg Dl_124940_;
tyProc_WFLTHAe29bld14aJj9beCK5A Dl_124949_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124956_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124959_;
tyProc_IDk3KxgJRpZTfHk6zjVF9cg Dl_124962_;
tyProc_v9bnMVZC9cjFuZKli9a20Vqqw Dl_124966_;
tyProc_F5LkdYXGj3yMMWLNUL9cLOA Dl_124970_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124976_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124979_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124982_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124985_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124988_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_124991_;
tyProc_t5KjWrxjUu40ao8Tp0V7XQ Dl_124994_;
tyProc_t5KjWrxjUu40ao8Tp0V7XQ Dl_124999_;
tyProc_339btklVCd1SL8BqHamG2Sw Dl_125004_;
tyProc_339btklVCd1SL8BqHamG2Sw Dl_125012_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_125020_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_125023_;
tyProc_b5dn4OpHEOlm9a7Vo89bfyBw Dl_125026_;
tyProc_339btklVCd1SL8BqHamG2Sw Dl_125029_;
tyProc_9aukviZdgv7BLiI3X9artC4Q Dl_125037_;
tyProc_4babc4K0ehjpA6BgPlEevw Dl_125040_;
tyProc_33NIE6G8GLZ7XfoluRBl6g Dl_125043_;
tyProc_VHjFICAr2J3eeACpQrvlug Dl_125045_;
tyProc_ScjVnXD428Cge0AhV0NjYA Dl_125048_;
tyProc_Lrd35sSswkqWXPt2LTy36g Dl_125051_;
tyProc_Mj5Jc7sZKtFxS9cLqfyVaOA Dl_125054_;
tyProc_CMwYVC7RjtSkJEY3ALD8zA Dl_125058_;
tyProc_ia27lCtds76qrQFLt6D1NQ Dl_125062_;
tyProc_9cAjRmXyG1GE3wa7ESpjJ9bg Dl_125065_;
tyProc_c9aWrPCbHK9azFxHs9bMRgkeg Dl_125069_;
tyProc_UXkckW9c5APvAZQCpiWtwaw Dl_125072_;
tyProc_Dy1F1Ti11YFnGBlcZukFxg Dl_125076_;
tyProc_9ajjrZ0cSz2C9anXqhwL6HEw Dl_125079_;
tyProc_uJWiMek9bz5a69cNCEbZoujw Dl_125083_;
tyProc_OJCP0679acdt5iiebX7nOtg Dl_125086_;
tyProc_ebhlAmxi6jQgAd0nXFRyvw Dl_125090_;
tyProc_fCq4b3nVFmfVbpQ9btjjtbw Dl_125093_;
tyProc_IDk3KxgJRpZTfHk6zjVF9cg Dl_125099_;
tyProc_K5FECQ0ybPb9atWPSnIi3VA Dl_125103_;
tyProc_K5FECQ0ybPb9atWPSnIi3VA Dl_125107_;
tyProc_YdesHI3MYrrRR08Jh7zhgQ Dl_125111_;
tyProc_YdesHI3MYrrRR08Jh7zhgQ Dl_125115_;
tyProc_47gYkL8UstHcH6pjkvyRuQ Dl_125119_;
tyProc_g9aqNx09cgnUoR7hwH6IZDKQ Dl_125123_;
tyProc_XdYFq9ck4QNcB9cvooxUk1uw Dl_125126_;
tyProc_nvcYXs1W2nD7FDtfIBQZ9cw Dl_125130_;
tyProc_a7UrMyL3x4LGrBOzeGOoMQ Dl_125133_;
tyProc_i9aN6X7KBEoLzyWf8K5DEMg Dl_125137_;
tyProc_a7UrMyL3x4LGrBOzeGOoMQ Dl_125142_;
tyProc_i9aN6X7KBEoLzyWf8K5DEMg Dl_125146_;
tyProc_CDvsVbFfhFwoVQCQF4otIQ Dl_125151_;
tyProc_bdoONiSmawyiu4BI2cS38A Dl_125156_;
tyProc_8a9aZys9anbr86hSlxaItX7w Dl_125162_;
tyProc_nDJK9aApXAKWYhxqqFWnVeA Dl_125166_;
tyProc_VWydpHmLvuDbDADfqZVm9cQ Dl_125169_;
tyProc_21dF9c72K6fJRyJ6KsNm1qA Dl_125172_;
tyProc_EGsm7wlcs9b0t5cKg3R9blrw Dl_125175_;
tyProc_S4bSrr6sfz9abNf9b5NnYvIQ Dl_125178_;
tyProc_qp0e6egyR7TRFBvIMUN2zQ Dl_125181_;
tyProc_OgAVtuI1sds9aPS4feUpKKw Dl_125185_;
tyProc_IaGyO0L5qZlmbYIaRkXYnw Dl_125191_;
tyProc_oqmnKiueAPhIfG5GiIVqpA Dl_125197_;
tyProc_rRipFnLK2R9a8uFeVDgP9ahA Dl_125200_;
tyProc_fC9a52vQNeTujfvy39b1ClCA Dl_125203_;
tyProc_C13HO6TYqLvda9b5bRGbrhQ Dl_125206_;
tyProc_9a6dQR84cnfZqWhvdW9brv6A Dl_125209_;
tyProc_UVuZMKiSo0MVveS5Wxh9b3A Dl_125212_;
tyProc_DjQFt0MiXawYyjjT9bWr9cZw Dl_125216_;
tyProc_QS4pIWzJA9bO3FDTc9c5WNQQ Dl_125222_;
tyProc_4NgXtH9atUOaCa9ca6ipUvSg Dl_125226_;
tyProc_5TuLcEoM6ARbOzfnsxfDcA Dl_125231_;
tyProc_Cylj9avAuP0mvXv8Z9aqGXDQ Dl_125237_;
tyProc_n1oDjTjHOH39cY9at4g7AuDw Dl_125240_;
tyProc_n1oDjTjHOH39cY9at4g7AuDw Dl_125244_;
tyProc_WlUK9aMj542mYOAb9bmJm7Jg Dl_125248_;
tyProc_7UgOQ2tsMSiCQMF0TLNXAQ Dl_125252_;
tyProc_yaV5mg4oeGskSsNHTsPaBA Dl_125255_;
tyProc_28zonchclHPmWSReHMwVyQ Dl_125258_;
tyProc_832GEpEK0JdEsAX1LFgWYw Dl_125261_;
tyProc_G1IzaTjB3nLZSlmIGBQ23Q Dl_125264_;
tyProc_6GAifTsaPCNyhtO6XTb2FA Dl_125270_;
tyProc_28zonchclHPmWSReHMwVyQ Dl_125273_;
tyProc_0gnDlYjBsggHJRI1EXo57g Dl_125276_;
tyProc_xmiaqgCIdhsWTdlQKgwNGQ Dl_125279_;
tyProc_28zonchclHPmWSReHMwVyQ Dl_125282_;
tyProc_003eudyNUy9c9c9bINdjNuXWQ Dl_125285_;
tyProc_G1IzaTjB3nLZSlmIGBQ23Q Dl_125288_;
tyProc_K5FECQ0ybPb9atWPSnIi3VA Dl_125294_;
tyProc_lo9aTFzzb9ctKr2AU61zDU6w Dl_125298_;
tyProc_lo9aTFzzb9ctKr2AU61zDU6w Dl_125301_;
tyProc_XeQF9bhOr2MD430IokV9cv8A Dl_125304_;
tyProc_XeQF9bhOr2MD430IokV9cv8A Dl_125307_;
tyProc_AXsKTk2AT34S84BOY0kX8A Dl_125310_;
tyProc_Phx1pnFtRjsF0U37Ztn1kA Dl_125314_;
tyProc_mR44TxkOMM9bNebf0XQCi9cw Dl_125317_;
tyProc_r5WpYAfpxEqrcCiGpWLHXQ Dl_125320_;
tyProc_XehrqkX6mJFP8d09b43s3fg Dl_125323_;
tyProc_c78ufLOvL9cbxy6S4zFU6zQ Dl_125329_;
tyProc_MSMGzSUseJ60axIE1SMYvw Dl_125332_;
tyProc_MSMGzSUseJ60axIE1SMYvw Dl_125335_;
tyProc_iAzWoI5ZgPU10dxrHCTufA Dl_125338_;
tyProc_mAFv9brcf06NIf9aBHn0n9coA Dl_125341_;
tyProc_PRzMR7K9b7Vlzxfu4uAh4oA Dl_125344_;
tyProc_GUY0uaMj5S6KSj14MSmESw Dl_125347_;
tyProc_wiBE3rmX3joDIm1hE5o6Bg Dl_125350_;
tyProc_hY9aJzK0lzZPab0BYxLz6aQ Dl_125354_;
tyProc_6KsatHUTy686VVpnNJFqsg Dl_125359_;
tyProc_ZoXFGrEmg3eJyqsmCbtYpg Dl_125363_;
tyProc_5s9bXD22uREj8Idfn4E33XQ Dl_125369_;
tyProc_MSMGzSUseJ60axIE1SMYvw Dl_125373_;
tyProc_MSMGzSUseJ60axIE1SMYvw Dl_125376_;
tyProc_9b4RHlxg89b1yB4rnlhtxLQQ Dl_125379_;
tyProc_ysQ8zhM82MX3e6sS4SpH4w Dl_125386_;
tyProc_9aatS6b0zXqkNGXFLvpleDA Dl_125391_;
tyProc_ysQ8zhM82MX3e6sS4SpH4w Dl_125397_;
tyProc_gBjtZoPOtjvOF4yccS4V7Q Dl_125402_;
tyProc_Uoita1I61h1gE7KHOrDawA Dl_125407_;
tyProc_hfgEFCmitG5OIl8OtxQGlw Dl_125414_;
tyProc_fM0MZsmwSRd2ie6RtsZTPg Dl_125417_;
tyProc_iAzWoI5ZgPU10dxrHCTufA Dl_125420_;
tyProc_iAzWoI5ZgPU10dxrHCTufA Dl_125423_;
tyProc_iAzWoI5ZgPU10dxrHCTufA Dl_125426_;
tyProc_hgZhJ8Q75gQUb9aku7HTKRA Dl_125429_;
tyProc_lFTTSaN5PhB0wXCiGfKZOw Dl_125432_;
tyProc_609a5FRdyzdkmQD49b5pZjtQ Dl_125436_;
tyProc_h9cpVNoNS9azUSdi23h4WrJA Dl_125441_;
tyProc_A39bwfAAhDNLh0wNH3v0GTw Dl_125447_;
tyProc_h9cpVNoNS9azUSdi23h4WrJA Dl_125450_;
tyProc_acSgkkZ5DDKO5QEU6ZLIKg Dl_125456_;
tyProc_wxC0L9cSbhFTW1O9cv9bSIOOQ Dl_125464_;
tyProc_fOn9bZgC2cIRrps71OVzqDw Dl_125467_;
tyProc_cjsfU9cNwS9aOVNpUSTZDdRg Dl_125470_;
tyProc_FUmpeEGlnmZIz4xTHDbNjw Dl_125473_;
tyProc_s9a9aABS1CxWyZ9aL9bKBjN4sQ Dl_125476_;
tyProc_pU9aF9a4LSX5Lq8he8uApwZA Dl_125480_;
tyProc_Aeb0lLI2E9bXlFuIc7Ot9c4g Dl_125486_;
tyProc_wAJSvEMQR3dsEE9adeaNR5g Dl_125489_;
tyProc_Z9c2Gh9bseNrq80paeWhiLvw Dl_125496_;
tyProc_na25J7cDhfHBnapdWR20ng Dl_125504_;
tyProc_na25J7cDhfHBnapdWR20ng Dl_125508_;
tyProc_b0cvLkOO6mAfu9cUHkAcH7A Dl_125512_;
tyProc_zL9bBsNSEjNx9anZGaPZNY3A Dl_125516_;
tyProc_KVWFtQxhyUqXCiNqJB0XdQ Dl_125519_;
tyProc_XJlMpSjcdRQ9cv1NS06k6wg Dl_125523_;
tyProc_4VXoJS9czZ8R5T9ascqzsAKA Dl_125526_;
tyProc_Ut1VYiCzyx4CmVjkGAA9aHw Dl_125534_;
tyProc_FmaS3degI3AzWSb7zwDGEg Dl_125538_;
tyProc_W8tksr9aQ8bLKbdGATtOVZQ Dl_125548_;
tyProc_4VXoJS9czZ8R5T9ascqzsAKA Dl_125553_;
tyProc_ncWD0dq9aoi3dz9aE2rjdkcw Dl_125561_;
tyProc_jCeHA0YLZ77AF1guqUdGLg Dl_125571_;
tyProc_zzhElsnicQsyaaf9ciyveLw Dl_125580_;
tyProc_0W09cnQPtlS5pZclissM9aPQ Dl_125583_;
tyProc_0W09cnQPtlS5pZclissM9aPQ Dl_125588_;
tyProc_V6TgiyXVtkiiGQ0z9cZmJBA Dl_125593_;
tyProc_0W09cnQPtlS5pZclissM9aPQ Dl_125597_;
tyProc_0W09cnQPtlS5pZclissM9aPQ Dl_125602_;
tyProc_V6TgiyXVtkiiGQ0z9cZmJBA Dl_125607_;
tyProc_gek9a89c05JDZDAKWud8hTpw Dl_125611_;
tyProc_HAFfIEfyf52E83kbhIan9aQ Dl_125614_;
tyProc_9cE0bBdbiT2zqc06U3dLL8g Dl_125619_;
tyProc_9cE0bBdbiT2zqc06U3dLL8g Dl_125625_;
tyProc_oXjJdMsROOz7shLxEUuTFg Dl_125631_;
tyProc_oPRl5xAHmhnhJRzAAN20nQ Dl_125636_;
tyProc_ysQ8zhM82MX3e6sS4SpH4w Dl_125642_;
tyProc_oXjJdMsROOz7shLxEUuTFg Dl_125647_;
tyProc_oPRl5xAHmhnhJRzAAN20nQ Dl_125652_;
tyProc_ysQ8zhM82MX3e6sS4SpH4w Dl_125658_;
tyProc_6mY1HXnIEx4tYTeCD0J3VQ Dl_125663_;
tyProc_MSMGzSUseJ60axIE1SMYvw Dl_125667_;
tyProc_MSMGzSUseJ60axIE1SMYvw Dl_125670_;
tyProc_oXjJdMsROOz7shLxEUuTFg Dl_125673_;
tyProc_oPRl5xAHmhnhJRzAAN20nQ Dl_125678_;
tyProc_td5ALJgXfT4IynJRSfZ0Ww Dl_125684_;
tyProc_e19a0rq9babSEwP7Rdc9bfPRA Dl_125688_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125691_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_ifzw1vprtw9c3P0ALO6wgRA_;
extern TNimType NTI_NrupLB36t9bV7iFDHtrF69aw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern TNimType NTI_TmgWlPUbRr7iGD2UE1cu6A_;
extern TNimType NTI_8FC9arcap3s5ZtfMs75krtA_;
tyProc_wE1dpGGgx7v5XgHCN8T0cQ Dl_125753_;
STRING_LITERAL(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_4, "libcairo.so", 11);
STRING_LITERAL(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_6, "libcairo.so.2", 13);
STRING_LITERAL(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_7, "libcairo.so(|.2)", 16);

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, version_NrV9b65DuwYQFfiBz19aMlZg)(NI32* major, NI32* minor, NI32* micro) {
	NI32 version;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_456;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_457;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_458;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_459;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_460;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_461;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_462;
	NI TM_vVBuhYNeXtg9ctjIG2Ce1IQ_463;
	nimfr_("version", "cairo.nim");
	version = (NI32)0;
	nimln_(720, "cairo.nim");
	version = Dl_124728_();
	nimln_(721, "cairo.nim");
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_456 = divInt(version, ((NI32) 10000));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_456 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_456 > 2147483647) raiseOverflow();
	(*major) = (NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_456);
	nimln_(722, "cairo.nim");
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_457 = mulInt((*major), ((NI32) 10000));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_457 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_457 > 2147483647) raiseOverflow();
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_458 = modInt(version, (NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_457));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_458 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_458 > 2147483647) raiseOverflow();
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_459 = divInt((NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_458), ((NI32) 100));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_459 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_459 > 2147483647) raiseOverflow();
	(*minor) = (NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_459);
	nimln_(723, "cairo.nim");
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_460 = mulInt((*major), ((NI32) 10000));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_460 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_460 > 2147483647) raiseOverflow();
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_461 = mulInt((*minor), ((NI32) 100));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_461 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_461 > 2147483647) raiseOverflow();
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_462 = addInt((NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_460), (NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_461));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_462 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_462 > 2147483647) raiseOverflow();
	TM_vVBuhYNeXtg9ctjIG2Ce1IQ_463 = modInt(version, (NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_462));
	if (TM_vVBuhYNeXtg9ctjIG2Ce1IQ_463 < (-2147483647 -1) || TM_vVBuhYNeXtg9ctjIG2Ce1IQ_463 > 2147483647) raiseOverflow();
	(*micro) = (NI32)(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_463);
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(381, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(381, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(381, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(381, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NOINLINE(void, checkStatus_2qpdTRrt4eXupJE86zN2hA)(tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg s) {
	nimfr_("checkStatus", "cairo.nim");
	nimln_(728, "cairo.nim");
	switch (s) {
	case ((tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg) 0):
	{
	}
	break;
	case ((tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg) 1):
	{
		tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw* e;
		NCSTRING T3_;
		e = (tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw*)0;
		nimln_(2712, "system.nim");
		e = (tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw*) newObj((&NTI_ifzw1vprtw9c3P0ALO6wgRA_), sizeof(tyObject_OutOfMemError_NrupLB36t9bV7iFDHtrF69aw));
		(*e).Sup.Sup.Sup.m_type = (&NTI_NrupLB36t9bV7iFDHtrF69aw_);
		nimln_(731, "cairo.nim");
		T3_ = (NCSTRING)0;
		T3_ = Dl_125320_(s);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), cstrToNimstr(T3_));
		nimln_(2707, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(731, "cairo.nim");
		raiseException((Exception*)e, "OutOfMemError");
	}
	break;
	case ((tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg) 10):
	case ((tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg) 11):
	case ((tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg) 18):
	case ((tyEnum_TStatus_VKtNk48qrdsHDKV9c9aLNPqg) 23):
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e_2;
		NCSTRING T5_;
		e_2 = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2712, "system.nim");
		e_2 = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e_2).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(734, "cairo.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_125320_(s);
		asgnRefNoCycle((void**) (&(*e_2).Sup.Sup.message), cstrToNimstr(T5_));
		nimln_(2707, "system.nim");
		asgnRef((void**) (&(*e_2).Sup.Sup.parent), NIM_NIL);
		nimln_(734, "cairo.nim");
		raiseException((Exception*)e_2, "IOError");
	}
	break;
	default:
	{
		tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA* e_3;
		NCSTRING T7_;
		e_3 = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*)0;
		nimln_(2712, "system.nim");
		e_3 = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*) newObj((&NTI_TmgWlPUbRr7iGD2UE1cu6A_), sizeof(tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA));
		(*e_3).Sup.Sup.m_type = (&NTI_8FC9arcap3s5ZtfMs75krtA_);
		nimln_(736, "cairo.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_125320_(s);
		asgnRefNoCycle((void**) (&(*e_3).Sup.message), cstrToNimstr(T7_));
		nimln_(2707, "system.nim");
		asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
		nimln_(736, "cairo.nim");
		raiseException((Exception*)e_3, "AssertionError");
	}
	break;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, cairo_cairoInit000)(void) {
	nimfr_("cairo", "cairo.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, cairo_cairoDatInit000)(void) {
if (!((TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2 = nimLoadLibrary((NimStringDesc*) &TM_vVBuhYNeXtg9ctjIG2Ce1IQ_4))
||(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2 = nimLoadLibrary((NimStringDesc*) &TM_vVBuhYNeXtg9ctjIG2Ce1IQ_6))
)) nimLoadLibraryError((NimStringDesc*) &TM_vVBuhYNeXtg9ctjIG2Ce1IQ_7);
	Dl_124728_ = (tyProc_07QdujGjOf8s9cNEpM0S9aKQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_version");
	Dl_124730_ = (tyProc_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_version_string");
	Dl_124738_ = (tyProc_bTW7Hl6B8eRPusBByIUiKg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_create");
	Dl_124741_ = (tyProc_RNX29bk9aCAILf0cldsQQigA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_reference");
	Dl_124744_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_destroy");
	Dl_124747_ = (tyProc_003eudyNUy9c9c9bINdjNuXWQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_reference_count");
	Dl_124750_ = (tyProc_25YgodgyVmLA8488tNz4KQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_user_data");
	Dl_124754_ = (tyProc_8SKnWuTMsmqaYOdEMDugaA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_user_data");
	Dl_124760_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_save");
	Dl_124763_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_restore");
	Dl_124766_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_push_group");
	Dl_124769_ = (tyProc_QFcosXU7VIBNlSp9c7ZlXVQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_push_group_with_content");
	Dl_124773_ = (tyProc_yaV5mg4oeGskSsNHTsPaBA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pop_group");
	Dl_124776_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pop_group_to_source");
	Dl_124779_ = (tyProc_xjXqSV7Q1FpO9cHdSpTYefw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_operator");
	Dl_124783_ = (tyProc_v9bnMVZC9cjFuZKli9a20Vqqw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_source");
	Dl_124787_ = (tyProc_Vig9bMGAwzJYDfhF79cygw0Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_source_rgb");
	Dl_124793_ = (tyProc_WFLTHAe29bld14aJj9beCK5A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_source_rgba");
	Dl_124800_ = (tyProc_F5LkdYXGj3yMMWLNUL9cLOA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_source_surface");
	Dl_124806_ = (tyProc_IDk3KxgJRpZTfHk6zjVF9cg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_tolerance");
	Dl_124810_ = (tyProc_VnOGDxkHZlQKTEdg9bzDacA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_antialias");
	Dl_124814_ = (tyProc_GKgVMGIR9bcSVTrGVlKCZUw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_fill_rule");
	Dl_124818_ = (tyProc_IDk3KxgJRpZTfHk6zjVF9cg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_line_width");
	Dl_124822_ = (tyProc_iejs3M9bTicev3z3gzifcvg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_line_cap");
	Dl_124826_ = (tyProc_VZZ8sQYIoEgFODl5stMqOQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_line_join");
	Dl_124830_ = (tyProc_lECD39bCmUBecTcvA0sUMNA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_dash");
	Dl_124836_ = (tyProc_IDk3KxgJRpZTfHk6zjVF9cg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_miter_limit");
	Dl_124840_ = (tyProc_8F2XGMxl7hq1cDz14pJs8w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_translate");
	Dl_124845_ = (tyProc_8F2XGMxl7hq1cDz14pJs8w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scale");
	Dl_124850_ = (tyProc_IDk3KxgJRpZTfHk6zjVF9cg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_rotate");
	Dl_124854_ = (tyProc_K5FECQ0ybPb9atWPSnIi3VA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_transform");
	Dl_124858_ = (tyProc_K5FECQ0ybPb9atWPSnIi3VA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_matrix");
	Dl_124862_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_identity_matrix");
	Dl_124865_ = (tyProc_G1IzaTjB3nLZSlmIGBQ23Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_user_to_device");
	Dl_124871_ = (tyProc_G1IzaTjB3nLZSlmIGBQ23Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_user_to_device_distance");
	Dl_124877_ = (tyProc_G1IzaTjB3nLZSlmIGBQ23Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_device_to_user");
	Dl_124883_ = (tyProc_G1IzaTjB3nLZSlmIGBQ23Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_device_to_user_distance");
	Dl_124889_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_new_path");
	Dl_124892_ = (tyProc_8F2XGMxl7hq1cDz14pJs8w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_move_to");
	Dl_124897_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_new_sub_path");
	Dl_124900_ = (tyProc_8F2XGMxl7hq1cDz14pJs8w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_line_to");
	Dl_124905_ = (tyProc_17SydyDYqHdll9c39brh1Oyg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_curve_to");
	Dl_124914_ = (tyProc_YMaQGOsqXjPV1HbRPnFGrg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_arc");
	Dl_124922_ = (tyProc_YMaQGOsqXjPV1HbRPnFGrg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_arc_negative");
	Dl_124930_ = (tyProc_8F2XGMxl7hq1cDz14pJs8w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_rel_move_to");
	Dl_124935_ = (tyProc_8F2XGMxl7hq1cDz14pJs8w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_rel_line_to");
	Dl_124940_ = (tyProc_17SydyDYqHdll9c39brh1Oyg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_rel_curve_to");
	Dl_124949_ = (tyProc_WFLTHAe29bld14aJj9beCK5A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_rectangle");
	Dl_124956_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_close_path");
	Dl_124959_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_paint");
	Dl_124962_ = (tyProc_IDk3KxgJRpZTfHk6zjVF9cg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_paint_with_alpha");
	Dl_124966_ = (tyProc_v9bnMVZC9cjFuZKli9a20Vqqw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_mask");
	Dl_124970_ = (tyProc_F5LkdYXGj3yMMWLNUL9cLOA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_mask_surface");
	Dl_124976_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_stroke");
	Dl_124979_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_stroke_preserve");
	Dl_124982_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_fill");
	Dl_124985_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_fill_preserve");
	Dl_124988_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_copy_page");
	Dl_124991_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_show_page");
	Dl_124994_ = (tyProc_t5KjWrxjUu40ao8Tp0V7XQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_in_stroke");
	Dl_124999_ = (tyProc_t5KjWrxjUu40ao8Tp0V7XQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_in_fill");
	Dl_125004_ = (tyProc_339btklVCd1SL8BqHamG2Sw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_stroke_extents");
	Dl_125012_ = (tyProc_339btklVCd1SL8BqHamG2Sw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_fill_extents");
	Dl_125020_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_reset_clip");
	Dl_125023_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_clip");
	Dl_125026_ = (tyProc_b5dn4OpHEOlm9a7Vo89bfyBw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_clip_preserve");
	Dl_125029_ = (tyProc_339btklVCd1SL8BqHamG2Sw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_clip_extents");
	Dl_125037_ = (tyProc_9aukviZdgv7BLiI3X9artC4Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_copy_clip_rectangle_list");
	Dl_125040_ = (tyProc_4babc4K0ehjpA6BgPlEevw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_rectangle_list_destroy");
	Dl_125043_ = (tyProc_33NIE6G8GLZ7XfoluRBl6g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_create");
	Dl_125045_ = (tyProc_VHjFICAr2J3eeACpQrvlug) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_copy");
	Dl_125048_ = (tyProc_ScjVnXD428Cge0AhV0NjYA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_destroy");
	Dl_125051_ = (tyProc_Lrd35sSswkqWXPt2LTy36g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_status");
	Dl_125054_ = (tyProc_Mj5Jc7sZKtFxS9cLqfyVaOA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_merge");
	Dl_125058_ = (tyProc_CMwYVC7RjtSkJEY3ALD8zA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_equal");
	Dl_125062_ = (tyProc_ia27lCtds76qrQFLt6D1NQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_hash");
	Dl_125065_ = (tyProc_9cAjRmXyG1GE3wa7ESpjJ9bg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_set_antialias");
	Dl_125069_ = (tyProc_c9aWrPCbHK9azFxHs9bMRgkeg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_get_antialias");
	Dl_125072_ = (tyProc_UXkckW9c5APvAZQCpiWtwaw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_set_subpixel_order");
	Dl_125076_ = (tyProc_Dy1F1Ti11YFnGBlcZukFxg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_get_subpixel_order");
	Dl_125079_ = (tyProc_9ajjrZ0cSz2C9anXqhwL6HEw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_set_hint_style");
	Dl_125083_ = (tyProc_uJWiMek9bz5a69cNCEbZoujw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_get_hint_style");
	Dl_125086_ = (tyProc_OJCP0679acdt5iiebX7nOtg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_set_hint_metrics");
	Dl_125090_ = (tyProc_ebhlAmxi6jQgAd0nXFRyvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_options_get_hint_metrics");
	Dl_125093_ = (tyProc_fCq4b3nVFmfVbpQ9btjjtbw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_select_font_face");
	Dl_125099_ = (tyProc_IDk3KxgJRpZTfHk6zjVF9cg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_font_size");
	Dl_125103_ = (tyProc_K5FECQ0ybPb9atWPSnIi3VA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_font_matrix");
	Dl_125107_ = (tyProc_K5FECQ0ybPb9atWPSnIi3VA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_font_matrix");
	Dl_125111_ = (tyProc_YdesHI3MYrrRR08Jh7zhgQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_font_options");
	Dl_125115_ = (tyProc_YdesHI3MYrrRR08Jh7zhgQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_font_options");
	Dl_125119_ = (tyProc_47gYkL8UstHcH6pjkvyRuQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_font_face");
	Dl_125123_ = (tyProc_g9aqNx09cgnUoR7hwH6IZDKQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_font_face");
	Dl_125126_ = (tyProc_XdYFq9ck4QNcB9cvooxUk1uw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_set_scaled_font");
	Dl_125130_ = (tyProc_nvcYXs1W2nD7FDtfIBQZ9cw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_scaled_font");
	Dl_125133_ = (tyProc_a7UrMyL3x4LGrBOzeGOoMQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_show_text");
	Dl_125137_ = (tyProc_i9aN6X7KBEoLzyWf8K5DEMg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_show_glyphs");
	Dl_125142_ = (tyProc_a7UrMyL3x4LGrBOzeGOoMQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_text_path");
	Dl_125146_ = (tyProc_i9aN6X7KBEoLzyWf8K5DEMg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_glyph_path");
	Dl_125151_ = (tyProc_CDvsVbFfhFwoVQCQF4otIQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_text_extents");
	Dl_125156_ = (tyProc_bdoONiSmawyiu4BI2cS38A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_glyph_extents");
	Dl_125162_ = (tyProc_8a9aZys9anbr86hSlxaItX7w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_extents");
	Dl_125166_ = (tyProc_nDJK9aApXAKWYhxqqFWnVeA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_reference");
	Dl_125169_ = (tyProc_VWydpHmLvuDbDADfqZVm9cQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_destroy");
	Dl_125172_ = (tyProc_21dF9c72K6fJRyJ6KsNm1qA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_get_reference_count");
	Dl_125175_ = (tyProc_EGsm7wlcs9b0t5cKg3R9blrw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_status");
	Dl_125178_ = (tyProc_S4bSrr6sfz9abNf9b5NnYvIQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_get_type");
	Dl_125181_ = (tyProc_qp0e6egyR7TRFBvIMUN2zQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_get_user_data");
	Dl_125185_ = (tyProc_OgAVtuI1sds9aPS4feUpKKw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_font_face_set_user_data");
	Dl_125191_ = (tyProc_IaGyO0L5qZlmbYIaRkXYnw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_create");
	Dl_125197_ = (tyProc_oqmnKiueAPhIfG5GiIVqpA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_reference");
	Dl_125200_ = (tyProc_rRipFnLK2R9a8uFeVDgP9ahA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_destroy");
	Dl_125203_ = (tyProc_fC9a52vQNeTujfvy39b1ClCA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_reference_count");
	Dl_125206_ = (tyProc_C13HO6TYqLvda9b5bRGbrhQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_status");
	Dl_125209_ = (tyProc_9a6dQR84cnfZqWhvdW9brv6A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_type");
	Dl_125212_ = (tyProc_UVuZMKiSo0MVveS5Wxh9b3A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_user_data");
	Dl_125216_ = (tyProc_DjQFt0MiXawYyjjT9bWr9cZw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_set_user_data");
	Dl_125222_ = (tyProc_QS4pIWzJA9bO3FDTc9c5WNQQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_extents");
	Dl_125226_ = (tyProc_4NgXtH9atUOaCa9ca6ipUvSg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_text_extents");
	Dl_125231_ = (tyProc_5TuLcEoM6ARbOzfnsxfDcA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_glyph_extents");
	Dl_125237_ = (tyProc_Cylj9avAuP0mvXv8Z9aqGXDQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_font_face");
	Dl_125240_ = (tyProc_n1oDjTjHOH39cY9at4g7AuDw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_font_matrix");
	Dl_125244_ = (tyProc_n1oDjTjHOH39cY9at4g7AuDw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_ctm");
	Dl_125248_ = (tyProc_WlUK9aMj542mYOAb9bmJm7Jg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_scaled_font_get_font_options");
	Dl_125252_ = (tyProc_7UgOQ2tsMSiCQMF0TLNXAQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_operator");
	Dl_125255_ = (tyProc_yaV5mg4oeGskSsNHTsPaBA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_source");
	Dl_125258_ = (tyProc_28zonchclHPmWSReHMwVyQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_tolerance");
	Dl_125261_ = (tyProc_832GEpEK0JdEsAX1LFgWYw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_antialias");
	Dl_125264_ = (tyProc_G1IzaTjB3nLZSlmIGBQ23Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_current_point");
	Dl_125270_ = (tyProc_6GAifTsaPCNyhtO6XTb2FA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_fill_rule");
	Dl_125273_ = (tyProc_28zonchclHPmWSReHMwVyQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_line_width");
	Dl_125276_ = (tyProc_0gnDlYjBsggHJRI1EXo57g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_line_cap");
	Dl_125279_ = (tyProc_xmiaqgCIdhsWTdlQKgwNGQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_line_join");
	Dl_125282_ = (tyProc_28zonchclHPmWSReHMwVyQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_miter_limit");
	Dl_125285_ = (tyProc_003eudyNUy9c9c9bINdjNuXWQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_dash_count");
	Dl_125288_ = (tyProc_G1IzaTjB3nLZSlmIGBQ23Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_dash");
	Dl_125294_ = (tyProc_K5FECQ0ybPb9atWPSnIi3VA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_matrix");
	Dl_125298_ = (tyProc_lo9aTFzzb9ctKr2AU61zDU6w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_target");
	Dl_125301_ = (tyProc_lo9aTFzzb9ctKr2AU61zDU6w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_get_group_target");
	Dl_125304_ = (tyProc_XeQF9bhOr2MD430IokV9cv8A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_copy_path");
	Dl_125307_ = (tyProc_XeQF9bhOr2MD430IokV9cv8A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_copy_path_flat");
	Dl_125310_ = (tyProc_AXsKTk2AT34S84BOY0kX8A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_append_path");
	Dl_125314_ = (tyProc_Phx1pnFtRjsF0U37Ztn1kA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_path_destroy");
	Dl_125317_ = (tyProc_mR44TxkOMM9bNebf0XQCi9cw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_status");
	Dl_125320_ = (tyProc_r5WpYAfpxEqrcCiGpWLHXQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_status_to_string");
	Dl_125323_ = (tyProc_XehrqkX6mJFP8d09b43s3fg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_create_similar");
	Dl_125329_ = (tyProc_c78ufLOvL9cbxy6S4zFU6zQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_reference");
	Dl_125332_ = (tyProc_MSMGzSUseJ60axIE1SMYvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_finish");
	Dl_125335_ = (tyProc_MSMGzSUseJ60axIE1SMYvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_destroy");
	Dl_125338_ = (tyProc_iAzWoI5ZgPU10dxrHCTufA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_get_reference_count");
	Dl_125341_ = (tyProc_mAFv9brcf06NIf9aBHn0n9coA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_status");
	Dl_125344_ = (tyProc_PRzMR7K9b7Vlzxfu4uAh4oA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_get_type");
	Dl_125347_ = (tyProc_GUY0uaMj5S6KSj14MSmESw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_get_content");
	Dl_125350_ = (tyProc_wiBE3rmX3joDIm1hE5o6Bg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_write_to_png");
	Dl_125354_ = (tyProc_hY9aJzK0lzZPab0BYxLz6aQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_write_to_png_stream");
	Dl_125359_ = (tyProc_6KsatHUTy686VVpnNJFqsg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_get_user_data");
	Dl_125363_ = (tyProc_ZoXFGrEmg3eJyqsmCbtYpg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_set_user_data");
	Dl_125369_ = (tyProc_5s9bXD22uREj8Idfn4E33XQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_get_font_options");
	Dl_125373_ = (tyProc_MSMGzSUseJ60axIE1SMYvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_flush");
	Dl_125376_ = (tyProc_MSMGzSUseJ60axIE1SMYvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_mark_dirty");
	Dl_125379_ = (tyProc_9b4RHlxg89b1yB4rnlhtxLQQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_mark_dirty_rectangle");
	Dl_125386_ = (tyProc_ysQ8zhM82MX3e6sS4SpH4w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_set_device_offset");
	Dl_125391_ = (tyProc_9aatS6b0zXqkNGXFLvpleDA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_get_device_offset");
	Dl_125397_ = (tyProc_ysQ8zhM82MX3e6sS4SpH4w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_set_fallback_resolution");
	Dl_125402_ = (tyProc_gBjtZoPOtjvOF4yccS4V7Q) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_create");
	Dl_125407_ = (tyProc_Uoita1I61h1gE7KHOrDawA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_create_for_data");
	Dl_125414_ = (tyProc_hfgEFCmitG5OIl8OtxQGlw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_get_data");
	Dl_125417_ = (tyProc_fM0MZsmwSRd2ie6RtsZTPg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_get_format");
	Dl_125420_ = (tyProc_iAzWoI5ZgPU10dxrHCTufA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_get_width");
	Dl_125423_ = (tyProc_iAzWoI5ZgPU10dxrHCTufA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_get_height");
	Dl_125426_ = (tyProc_iAzWoI5ZgPU10dxrHCTufA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_get_stride");
	Dl_125429_ = (tyProc_hgZhJ8Q75gQUb9aku7HTKRA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_create_from_png");
	Dl_125432_ = (tyProc_lFTTSaN5PhB0wXCiGfKZOw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_image_surface_create_from_png_stream");
	Dl_125436_ = (tyProc_609a5FRdyzdkmQD49b5pZjtQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_create_rgb");
	Dl_125441_ = (tyProc_h9cpVNoNS9azUSdi23h4WrJA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_create_rgba");
	Dl_125447_ = (tyProc_A39bwfAAhDNLh0wNH3v0GTw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_create_for_surface");
	Dl_125450_ = (tyProc_h9cpVNoNS9azUSdi23h4WrJA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_create_linear");
	Dl_125456_ = (tyProc_acSgkkZ5DDKO5QEU6ZLIKg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_create_radial");
	Dl_125464_ = (tyProc_wxC0L9cSbhFTW1O9cv9bSIOOQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_reference");
	Dl_125467_ = (tyProc_fOn9bZgC2cIRrps71OVzqDw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_destroy");
	Dl_125470_ = (tyProc_cjsfU9cNwS9aOVNpUSTZDdRg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_reference_count");
	Dl_125473_ = (tyProc_FUmpeEGlnmZIz4xTHDbNjw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_status");
	Dl_125476_ = (tyProc_s9a9aABS1CxWyZ9aL9bKBjN4sQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_user_data");
	Dl_125480_ = (tyProc_pU9aF9a4LSX5Lq8he8uApwZA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_set_user_data");
	Dl_125486_ = (tyProc_Aeb0lLI2E9bXlFuIc7Ot9c4g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_type");
	Dl_125489_ = (tyProc_wAJSvEMQR3dsEE9adeaNR5g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_add_color_stop_rgb");
	Dl_125496_ = (tyProc_Z9c2Gh9bseNrq80paeWhiLvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_add_color_stop_rgba");
	Dl_125504_ = (tyProc_na25J7cDhfHBnapdWR20ng) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_set_matrix");
	Dl_125508_ = (tyProc_na25J7cDhfHBnapdWR20ng) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_matrix");
	Dl_125512_ = (tyProc_b0cvLkOO6mAfu9cUHkAcH7A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_set_extend");
	Dl_125516_ = (tyProc_zL9bBsNSEjNx9anZGaPZNY3A) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_extend");
	Dl_125519_ = (tyProc_KVWFtQxhyUqXCiNqJB0XdQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_set_filter");
	Dl_125523_ = (tyProc_XJlMpSjcdRQ9cv1NS06k6wg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_filter");
	Dl_125526_ = (tyProc_4VXoJS9czZ8R5T9ascqzsAKA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_rgba");
	Dl_125534_ = (tyProc_Ut1VYiCzyx4CmVjkGAA9aHw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_surface");
	Dl_125538_ = (tyProc_FmaS3degI3AzWSb7zwDGEg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_color_stop_rgba");
	Dl_125548_ = (tyProc_W8tksr9aQ8bLKbdGATtOVZQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_color_stop_count");
	Dl_125553_ = (tyProc_4VXoJS9czZ8R5T9ascqzsAKA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_linear_points");
	Dl_125561_ = (tyProc_ncWD0dq9aoi3dz9aE2rjdkcw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pattern_get_radial_circles");
	Dl_125571_ = (tyProc_jCeHA0YLZ77AF1guqUdGLg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_init");
	Dl_125580_ = (tyProc_zzhElsnicQsyaaf9ciyveLw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_init_identity");
	Dl_125583_ = (tyProc_0W09cnQPtlS5pZclissM9aPQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_init_translate");
	Dl_125588_ = (tyProc_0W09cnQPtlS5pZclissM9aPQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_init_scale");
	Dl_125593_ = (tyProc_V6TgiyXVtkiiGQ0z9cZmJBA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_init_rotate");
	Dl_125597_ = (tyProc_0W09cnQPtlS5pZclissM9aPQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_translate");
	Dl_125602_ = (tyProc_0W09cnQPtlS5pZclissM9aPQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_scale");
	Dl_125607_ = (tyProc_V6TgiyXVtkiiGQ0z9cZmJBA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_rotate");
	Dl_125611_ = (tyProc_gek9a89c05JDZDAKWud8hTpw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_invert");
	Dl_125614_ = (tyProc_HAFfIEfyf52E83kbhIan9aQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_multiply");
	Dl_125619_ = (tyProc_9cE0bBdbiT2zqc06U3dLL8g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_transform_distance");
	Dl_125625_ = (tyProc_9cE0bBdbiT2zqc06U3dLL8g) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_matrix_transform_point");
	Dl_125631_ = (tyProc_oXjJdMsROOz7shLxEUuTFg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pdf_surface_create");
	Dl_125636_ = (tyProc_oPRl5xAHmhnhJRzAAN20nQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pdf_surface_create_for_stream");
	Dl_125642_ = (tyProc_ysQ8zhM82MX3e6sS4SpH4w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_pdf_surface_set_size");
	Dl_125647_ = (tyProc_oXjJdMsROOz7shLxEUuTFg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_ps_surface_create");
	Dl_125652_ = (tyProc_oPRl5xAHmhnhJRzAAN20nQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_ps_surface_create_for_stream");
	Dl_125658_ = (tyProc_ysQ8zhM82MX3e6sS4SpH4w) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_ps_surface_set_size");
	Dl_125663_ = (tyProc_6mY1HXnIEx4tYTeCD0J3VQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_ps_surface_dsc_comment");
	Dl_125667_ = (tyProc_MSMGzSUseJ60axIE1SMYvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_ps_surface_dsc_begin_setup");
	Dl_125670_ = (tyProc_MSMGzSUseJ60axIE1SMYvw) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_ps_surface_dsc_begin_page_setup");
	Dl_125673_ = (tyProc_oXjJdMsROOz7shLxEUuTFg) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_svg_surface_create");
	Dl_125678_ = (tyProc_oPRl5xAHmhnhJRzAAN20nQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_svg_surface_create_for_stream");
	Dl_125684_ = (tyProc_td5ALJgXfT4IynJRSfZ0Ww) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_svg_surface_restrict_to_version");
	Dl_125688_ = (tyProc_e19a0rq9babSEwP7Rdc9bfPRA) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_svg_version_to_string");
	Dl_125691_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_debug_reset_static_data");
	Dl_125753_ = (tyProc_wE1dpGGgx7v5XgHCN8T0cQ) nimGetProcAddr(TM_vVBuhYNeXtg9ctjIG2Ce1IQ_2, "cairo_surface_create_for_rectangle");
}

