/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/t0rmund/devel/nim/lib -o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/dialog_types.o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/dialog_types.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_pt9brTQdXTI4a3rvyv9bPLOA tyTuple_pt9brTQdXTI4a3rvyv9bPLOA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence_jwzrUFjG9akTIJTBBFvvqxw tySequence_jwzrUFjG9akTIJTBBFvvqxw;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg tyTuple_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg;
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
struct tyTuple_pt9brTQdXTI4a3rvyv9bPLOA {
tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
NimStringDesc* Field3;
NimStringDesc* Field4;
tySequence_jwzrUFjG9akTIJTBBFvvqxw* Field5;
};
struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_jwzrUFjG9akTIJTBBFvvqxw {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, checkExtensionOnSave_iwSvCNUKUzzQSQe1bblOnA)(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA* di, NimStringDesc** res);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, tyTuple_7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_XOVT24GHXwqiEj5GCsEGCA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_pt9brTQdXTI4a3rvyv9bPLOA_;
TNimType NTI_JFweU9bdIxrlcwAU16YwFQg_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_jwzrUFjG9akTIJTBBFvvqxw_;

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, checkExtensionOnSave_iwSvCNUKUzzQSQe1bblOnA)(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA* di, NimStringDesc** res) {
	nimfr_("checkExtensionOnSave", "dialog_types.nim");
	nimln_(21, "dialog_types.nim");
	{
		NIM_BOOL T3_;
		tyTuple_7q7q3E6Oj24ZNVJb9aonhAg spr;
		T3_ = (NIM_BOOL)0;
		T3_ = ((*di).Field0 == ((tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg) 1));
		if (!(T3_)) goto LA4_;
		T3_ = (((NI) 0) < ((*di).Field4 ? (*di).Field4->Sup.len : 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		memset((void*)(&spr), 0, sizeof(spr));
		nimln_(22, "dialog_types.nim");
		chckNil((void*)(&spr));
		memset((void*)(&spr), 0, sizeof(spr));
		nossplitFile((*res), (&spr));
		nimln_(23, "dialog_types.nim");
		{
			if (!((spr.Field2 ? spr.Field2->Sup.len : 0) <= ((NI) 1))) goto LA9_;
			nimln_(24, "dialog_types.nim");
			{
				if (!((spr.Field2 ? spr.Field2->Sup.len : 0) == ((NI) 0))) goto LA13_;
				nimln_(25, "dialog_types.nim");
				(*res) = addChar((*res), 46);
			}
			LA13_: ;
			nimln_(26, "dialog_types.nim");
			(*res) = resizeString((*res), (*di).Field4->Sup.len + 0);
appendString((*res), (*di).Field4);
		}
		LA9_: ;
	}
	LA5_: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_dialog_typesInit000)(void) {
	nimfr_("dialog_types", "dialog_types.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_dialog_typesDatInit000)(void) {
static TNimNode* TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_2[2];
static TNimNode* TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[6];
static TNimNode* TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_4[4];
NI TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6;
static char* NIM_CONST TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_5[4] = {
"dkSelectFile", 
"dkSaveFile", 
"dkSelectFolder", 
"dkCreateFolder"};
static TNimNode TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[15];
NTI_XOVT24GHXwqiEj5GCsEGCA_.size = sizeof(tyTuple_XOVT24GHXwqiEj5GCsEGCA);
NTI_XOVT24GHXwqiEj5GCsEGCA_.kind = 18;
NTI_XOVT24GHXwqiEj5GCsEGCA_.base = 0;
NTI_XOVT24GHXwqiEj5GCsEGCA_.flags = 2;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_2[0] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[1];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[1].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[1].offset = offsetof(tyTuple_XOVT24GHXwqiEj5GCsEGCA, Field0);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[1].name = "Field0";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_2[1] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[2];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[2].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[2].offset = offsetof(tyTuple_XOVT24GHXwqiEj5GCsEGCA, Field1);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[2].name = "Field1";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[0].len = 2; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[0].kind = 2; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[0].sons = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_2[0];
NTI_XOVT24GHXwqiEj5GCsEGCA_.node = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[0];
NTI_pt9brTQdXTI4a3rvyv9bPLOA_.size = sizeof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA);
NTI_pt9brTQdXTI4a3rvyv9bPLOA_.kind = 18;
NTI_pt9brTQdXTI4a3rvyv9bPLOA_.base = 0;
NTI_pt9brTQdXTI4a3rvyv9bPLOA_.flags = 2;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[0] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[4];
NTI_JFweU9bdIxrlcwAU16YwFQg_.size = sizeof(tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg);
NTI_JFweU9bdIxrlcwAU16YwFQg_.kind = 14;
NTI_JFweU9bdIxrlcwAU16YwFQg_.base = 0;
NTI_JFweU9bdIxrlcwAU16YwFQg_.flags = 3;
for (TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6 = 0; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6 < 4; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6++) {
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6+5].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6+5].offset = TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6+5].name = TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_5[TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_4[TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_6+5];
}
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[9].len = 4; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[9].kind = 2; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[9].sons = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_4[0];
NTI_JFweU9bdIxrlcwAU16YwFQg_.node = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[9];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[4].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[4].offset = offsetof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA, Field0);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[4].typ = (&NTI_JFweU9bdIxrlcwAU16YwFQg_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[4].name = "Field0";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[1] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[10];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[10].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[10].offset = offsetof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA, Field1);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[10].name = "Field1";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[2] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[11];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[11].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[11].offset = offsetof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA, Field2);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[11].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[11].name = "Field2";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[3] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[12];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[12].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[12].offset = offsetof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA, Field3);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[12].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[12].name = "Field3";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[4] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[13];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[13].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[13].offset = offsetof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA, Field4);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[13].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[13].name = "Field4";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[5] = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[14];
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[14].kind = 1;
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[14].offset = offsetof(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA, Field5);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[14].typ = (&NTI_jwzrUFjG9akTIJTBBFvvqxw_);
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[14].name = "Field5";
TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[3].len = 6; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[3].kind = 2; TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[3].sons = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_3[0];
NTI_pt9brTQdXTI4a3rvyv9bPLOA_.node = &TM_9ccU9cBU9cZxTVbBVN9aEtBKSA_0[3];
}

