/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/t0rmund/devel/nim/lib -o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/gtk2_gtk2.o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/gtk2_gtk2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA;
typedef struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw;
typedef struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA;
typedef struct tyObject_TDialog_ebWAjsBELk37O6OlDglHLw tyObject_TDialog_ebWAjsBELk37O6OlDglHLw;
typedef struct tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ;
typedef struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA;
typedef struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w;
typedef struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ;
typedef struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg;
typedef struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ;
typedef struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ;
typedef struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ tyObject_TStyle_9b5KThw81CgYurztY67hTiQ;
typedef struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg;
typedef struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw;
typedef struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg;
typedef struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg;
typedef struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg;
typedef struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw;
typedef struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg;
typedef struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw;
typedef struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA;
typedef struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ;
typedef struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA;
typedef struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ;
typedef struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ;
typedef struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw;
typedef struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA;
typedef struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ;
typedef struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg;
typedef NCSTRING tyArray_M0HRG1TxfsgVFfIesgAGBg[256];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, tyProc_LCJy9bQFEE8ObaRc29a4n3LA) (void* argc, void* argv);
typedef NU8 tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g;
typedef N_CDECL_PTR(tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA*, tyProc_9bOzc7UlDODnFkXwgIFRMhQ) (NCSTRING title, tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* parent, tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g action, NCSTRING first_button_text, ...);
typedef N_CDECL_PTR(tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*, tyProc_cT6nc9bTXuu7BJHX4b3B2zw) (tyObject_TDialog_ebWAjsBELk37O6OlDglHLw* dialog, NCSTRING button_text, int response_id);
typedef N_CDECL_PTR(int, tyProc_cdf3zj2SHJFUTOjrJqabGQ) (tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* chooser, NCSTRING filename);
typedef N_CDECL_PTR(tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ*, tyProc_DozXQSyXdATJiFNw9cGbNUw) (void);
typedef N_CDECL_PTR(void, tyProc_hHzk7h6h9bFcD2HfWQwRJYg) (tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ* filter, NCSTRING pattern);
typedef N_CDECL_PTR(void, tyProc_oibsqiXOm4p4sjxDY49aLkA) (tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* chooser, tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ* filter);
typedef N_CDECL_PTR(int, tyProc_fEK6vbvxQgPdAeHQUcvIEg) (tyObject_TDialog_ebWAjsBELk37O6OlDglHLw* dialog);
typedef N_CDECL_PTR(NCSTRING, tyProc_RHLu5VhvToWoKn2DdN5gIg) (tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* chooser);
typedef N_CDECL_PTR(void, tyProc_VoMKl77iPAbE7kH39bhiGLA) (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* widget);
typedef N_CDECL_PTR(int, tyProc_BBveUfKT9b2ZY0NnHp9cisMg) (void);
struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ {
tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ* g_class;
};
struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg {
tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ g_type_instance;
NU32 ref_count;
void* qdata;
};
struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NU32 flags;
};
struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg {
int width;
int height;
};
struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw {
int x;
int y;
int width;
int height;
};
struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA {
  tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ Sup;
NU16 private_flags;
NU8 state;
NU8 saved_state;
NCSTRING name;
tyObject_TStyle_9b5KThw81CgYurztY67hTiQ* style;
tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg requisition;
tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw allocation;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* window;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* parent;
};
struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w {
  tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_child;
NU32 Container_flag0;
};
struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* child;
};
struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw {
  tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA Sup;
NCSTRING title;
NCSTRING wmclass_name;
NCSTRING wmclass_class;
NCSTRING wm_role;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_widget;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* default_widget;
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* transient_parent;
void* geometry_info;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* frame;
tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg* group;
NU16 configure_request_count;
NU32 window_flag0;
NU32 frame_left;
NU32 frame_top;
NU32 frame_right;
NU32 frame_bottom;
NU32 keys_changed_handler;
NU32 mnemonic_modifier;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
struct tyObject_TDialog_ebWAjsBELk37O6OlDglHLw {
  tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw Sup;
tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw* vbox;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* action_area;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* separator;
};
struct tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA {
  tyObject_TDialog_ebWAjsBELk37O6OlDglHLw Sup;
};
struct tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ {
char dummy;
};
struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ {
unsigned long g_type;
};
struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg {
NU32 pixel;
NU16 red;
NU16 green;
NU16 blue;
};
typedef tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyArray_9chWiMwZsMCYI2hkwl9cKGsg[5];
typedef tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* tyArray_mhiVER3NxWObr8Zo003MOg[5];
typedef tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ* tyArray_9a8bp6zR07xOSfUOBUwiOJQ[5];
struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg light;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg dark;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg mid;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text_aa;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg black;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg white;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
int xthickness;
int ythickness;
tyArray_mhiVER3NxWObr8Zo003MOg fg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg bg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg light_gc;
tyArray_mhiVER3NxWObr8Zo003MOg dark_gc;
tyArray_mhiVER3NxWObr8Zo003MOg mid_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_gc;
tyArray_mhiVER3NxWObr8Zo003MOg base_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_aa_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* black_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* white_gc;
tyArray_9a8bp6zR07xOSfUOBUwiOJQ bg_pixmap;
NU32 attach_count;
int depth;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ* private_font;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* private_font_desc;
tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ* rc_style;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* styles;
void* property_cache;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
};
struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* grabs;
};
struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* children;
NI16 spacing;
NU16 box_flag0;
};
struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw {
char dummy;
};
struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int clip_x_origin;
int clip_y_origin;
int ts_x_origin;
int ts_y_origin;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
};
struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int size;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg* colors;
tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg* visual;
void* windowing_data;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
typedef NU8 tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg;
struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ {
tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg type_0;
int ascent;
int descent;
};
typedef NCSTRING tyArray_J70ZWTopZxz1yNsmbJgQug[5];
typedef NI32 tyArray_CWoQ39cMobP9audxQ5BU3NgA[5];
struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NCSTRING name;
tyArray_J70ZWTopZxz1yNsmbJgQug bg_pixmap_name;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
tyArray_CWoQ39cMobP9audxQ5BU3NgA color_flags;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
int xthickness;
int ythickness;
void* rc_properties;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* rc_style_lists;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
NU16 RcStyle_flag0;
};
struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw {
void* data;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* next;
};
struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ {
void* data;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* next;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* prev;
};
typedef NU8 tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ;
typedef NU8 tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ;
struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ TheType;
int depth;
tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ byte_order;
int colormap_size;
int bits_per_rgb;
NU32 red_mask;
int red_shift;
int red_prec;
NU32 green_mask;
int green_shift;
int green_prec;
NU32 blue_mask;
int blue_shift;
int blue_prec;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_hZetKJO9brljcjvVpohVOXg_2;
tyProc_LCJy9bQFEE8ObaRc29a4n3LA Dl_152621_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_9bOzc7UlDODnFkXwgIFRMhQ Dl_180576_;
tyProc_cT6nc9bTXuu7BJHX4b3B2zw Dl_147922_;
tyProc_cdf3zj2SHJFUTOjrJqabGQ Dl_180864_;
tyProc_DozXQSyXdATJiFNw9cGbNUw Dl_180756_;
tyProc_hHzk7h6h9bFcD2HfWQwRJYg Dl_180769_;
tyProc_oibsqiXOm4p4sjxDY49aLkA Dl_180941_;
tyProc_fEK6vbvxQgPdAeHQUcvIEg Dl_147947_;
tyProc_RHLu5VhvToWoKn2DdN5gIg Dl_180840_;
tyProc_VoMKl77iPAbE7kH39bhiGLA Dl_144086_;
tyProc_BBveUfKT9b2ZY0NnHp9cisMg Dl_152613_;
tyProc_BBveUfKT9b2ZY0NnHp9cisMg Dl_152629_;
STRING_LITERAL(TM_hZetKJO9brljcjvVpohVOXg_4, "libgtk-x11-2.0.so", 17);
STRING_LITERAL(TM_hZetKJO9brljcjvVpohVOXg_6, "libgtk-x11-2.0.so.0", 19);
STRING_LITERAL(TM_hZetKJO9brljcjvVpohVOXg_7, "libgtk-x11-2.0.so(|.0)", 22);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, nim_init_BI4x6i9c40Tf9b1BitVLexNw)(void) {
	tyArray_M0HRG1TxfsgVFfIesgAGBg cmdLine;
	int cmdCount;
	nimfr_("nim_init", "gtk2.nim");
	memset((void*)cmdLine, 0, sizeof(cmdLine));
	cmdCount = (int)0;
	nimln_(17102, "gtk2.nim");
	Dl_152621_(((void*) (cmdLine)), ((void*) ((&cmdCount))));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, gtk2_gtk2Init000)(void) {
	nimfr_("gtk2", "gtk2.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gtk2_gtk2DatInit000)(void) {
if (!((TM_hZetKJO9brljcjvVpohVOXg_2 = nimLoadLibrary((NimStringDesc*) &TM_hZetKJO9brljcjvVpohVOXg_4))
||(TM_hZetKJO9brljcjvVpohVOXg_2 = nimLoadLibrary((NimStringDesc*) &TM_hZetKJO9brljcjvVpohVOXg_6))
)) nimLoadLibraryError((NimStringDesc*) &TM_hZetKJO9brljcjvVpohVOXg_7);
	Dl_152621_ = (tyProc_LCJy9bQFEE8ObaRc29a4n3LA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_init");
	Dl_180576_ = (tyProc_9bOzc7UlDODnFkXwgIFRMhQ) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_file_chooser_dialog_new");
	Dl_147922_ = (tyProc_cT6nc9bTXuu7BJHX4b3B2zw) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_dialog_add_button");
	Dl_180864_ = (tyProc_cdf3zj2SHJFUTOjrJqabGQ) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_file_chooser_set_current_folder");
	Dl_180756_ = (tyProc_DozXQSyXdATJiFNw9cGbNUw) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_file_filter_new");
	Dl_180769_ = (tyProc_hHzk7h6h9bFcD2HfWQwRJYg) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_file_filter_add_pattern");
	Dl_180941_ = (tyProc_oibsqiXOm4p4sjxDY49aLkA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_file_chooser_set_filter");
	Dl_147947_ = (tyProc_fEK6vbvxQgPdAeHQUcvIEg) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_dialog_run");
	Dl_180840_ = (tyProc_RHLu5VhvToWoKn2DdN5gIg) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_file_chooser_get_filename");
	Dl_144086_ = (tyProc_VoMKl77iPAbE7kH39bhiGLA) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_widget_destroy");
	Dl_152613_ = (tyProc_BBveUfKT9b2ZY0NnHp9cisMg) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_events_pending");
	Dl_152629_ = (tyProc_BBveUfKT9b2ZY0NnHp9cisMg) nimGetProcAddr(TM_hZetKJO9brljcjvVpohVOXg_2, "gtk_main_iteration");
}

