/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/t0rmund/devel/nim/lib -o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/unix_dialog.o /home/t0rmund/devel/native_file_dialog/native_file_dialog/nimcache/unix_dialog.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_jwzrUFjG9akTIJTBBFvvqxw tySequence_jwzrUFjG9akTIJTBBFvvqxw;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_pt9brTQdXTI4a3rvyv9bPLOA tyTuple_pt9brTQdXTI4a3rvyv9bPLOA;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA;
typedef struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw;
typedef struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA;
typedef struct tyObject_TDialog_ebWAjsBELk37O6OlDglHLw tyObject_TDialog_ebWAjsBELk37O6OlDglHLw;
typedef struct tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ;
typedef struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA;
typedef struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w;
typedef struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ;
typedef struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg;
typedef struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ;
typedef struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ;
typedef struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ tyObject_TStyle_9b5KThw81CgYurztY67hTiQ;
typedef struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg;
typedef struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw;
typedef struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg;
typedef struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg;
typedef struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg;
typedef struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw;
typedef struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg;
typedef struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw;
typedef struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA;
typedef struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ;
typedef struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA;
typedef struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ;
typedef struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ;
typedef struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw;
typedef struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA;
typedef struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ;
typedef struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g;
typedef NU8 tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg;
struct tyTuple_pt9brTQdXTI4a3rvyv9bPLOA {
tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
NimStringDesc* Field3;
NimStringDesc* Field4;
tySequence_jwzrUFjG9akTIJTBBFvvqxw* Field5;
};
typedef N_CDECL_PTR(tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA*, tyProc_9bOzc7UlDODnFkXwgIFRMhQ) (NCSTRING title, tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* parent, tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g action, NCSTRING first_button_text, ...);
typedef N_CDECL_PTR(tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*, tyProc_cT6nc9bTXuu7BJHX4b3B2zw) (tyObject_TDialog_ebWAjsBELk37O6OlDglHLw* dialog, NCSTRING button_text, int response_id);
typedef N_CDECL_PTR(int, tyProc_cdf3zj2SHJFUTOjrJqabGQ) (tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* chooser, NCSTRING filename);
typedef N_CDECL_PTR(tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ*, tyProc_DozXQSyXdATJiFNw9cGbNUw) (void);
typedef N_CDECL_PTR(void, tyProc_hHzk7h6h9bFcD2HfWQwRJYg) (tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ* filter, NCSTRING pattern);
typedef N_CDECL_PTR(void, tyProc_oibsqiXOm4p4sjxDY49aLkA) (tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* chooser, tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ* filter);
typedef N_CDECL_PTR(int, tyProc_fEK6vbvxQgPdAeHQUcvIEg) (tyObject_TDialog_ebWAjsBELk37O6OlDglHLw* dialog);
typedef N_CDECL_PTR(NCSTRING, tyProc_RHLu5VhvToWoKn2DdN5gIg) (tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* chooser);
typedef N_CDECL_PTR(void, tyProc_VoMKl77iPAbE7kH39bhiGLA) (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* widget);
typedef N_CDECL_PTR(int, tyProc_BBveUfKT9b2ZY0NnHp9cisMg) (void);
struct tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ {
tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ* g_class;
};
struct tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg {
tyObject_TGTypeInstance_Hd5q9bCXDPVyLVJ5JdgrMQQ g_type_instance;
NU32 ref_count;
void* qdata;
};
struct tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NU32 flags;
};
struct tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg {
int width;
int height;
};
struct tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw {
int x;
int y;
int width;
int height;
};
struct tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA {
  tyObject_TObject_HTzjrx4rsP4cOEBxAo33lQ Sup;
NU16 private_flags;
NU8 state;
NU8 saved_state;
NCSTRING name;
tyObject_TStyle_9b5KThw81CgYurztY67hTiQ* style;
tyObject_TRequisition_W6Zhq8Hhr9cAh09cOCmtEhNg requisition;
tyObject_TRectangle_zv79aTxCsIC8EGKnT9bKy9ahw allocation;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* window;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* parent;
};
struct tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w {
  tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_child;
NU32 Container_flag0;
};
struct tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* child;
};
struct tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw {
  tyObject_TBin_9cHkzsi229b8hbh9bi8FcxBLA Sup;
NCSTRING title;
NCSTRING wmclass_name;
NCSTRING wmclass_class;
NCSTRING wm_role;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* focus_widget;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* default_widget;
tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw* transient_parent;
void* geometry_info;
tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg* frame;
tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg* group;
NU16 configure_request_count;
NU32 window_flag0;
NU32 frame_left;
NU32 frame_top;
NU32 frame_right;
NU32 frame_bottom;
NU32 keys_changed_handler;
NU32 mnemonic_modifier;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
struct tyObject_TDialog_ebWAjsBELk37O6OlDglHLw {
  tyObject_TWindow_9c0QOTOK8kvZUQWJ8B9cJGLw Sup;
tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw* vbox;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* action_area;
tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* separator;
};
struct tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA {
  tyObject_TDialog_ebWAjsBELk37O6OlDglHLw Sup;
};
struct tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ {
char dummy;
};
struct tyObject_TGTypeClass_LR9cRbSaRO6tV8q2yA9a5vnQ {
unsigned long g_type;
};
struct tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg {
NU32 pixel;
NU16 red;
NU16 green;
NU16 blue;
};
typedef tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg tyArray_9chWiMwZsMCYI2hkwl9cKGsg[5];
typedef tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* tyArray_mhiVER3NxWObr8Zo003MOg[5];
typedef tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ* tyArray_9a8bp6zR07xOSfUOBUwiOJQ[5];
struct tyObject_TStyle_9b5KThw81CgYurztY67hTiQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg light;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg dark;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg mid;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text_aa;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg black;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg white;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
int xthickness;
int ythickness;
tyArray_mhiVER3NxWObr8Zo003MOg fg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg bg_gc;
tyArray_mhiVER3NxWObr8Zo003MOg light_gc;
tyArray_mhiVER3NxWObr8Zo003MOg dark_gc;
tyArray_mhiVER3NxWObr8Zo003MOg mid_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_gc;
tyArray_mhiVER3NxWObr8Zo003MOg base_gc;
tyArray_mhiVER3NxWObr8Zo003MOg text_aa_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* black_gc;
tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA* white_gc;
tyArray_9a8bp6zR07xOSfUOBUwiOJQ bg_pixmap;
NU32 attach_count;
int depth;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ* private_font;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* private_font_desc;
tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ* rc_style;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* styles;
void* property_cache;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
};
struct tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TWindow_IBnu9csXlSyWZ5uPFA25VHg {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TWindowGroup_EpOTvu0L6KDa6ei9bBGUHGg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* grabs;
};
struct tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
};
struct tyObject_TBox_9cWOlDpXQG3jqlcAaZu29bGw {
  tyObject_TContainer_PM431SlljJ9aj29cu7zO4e1w Sup;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* children;
NI16 spacing;
NU16 box_flag0;
};
struct tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw {
char dummy;
};
struct tyObject_TGC_ip4l9cYawwXEO9bo6bHUPOsA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int clip_x_origin;
int clip_y_origin;
int ts_x_origin;
int ts_y_origin;
tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA* colormap;
};
struct tyObject_TPixmap_se9ajBlC8Z9bf4t8bWmd3VsQ {
  tyObject_TDrawable_9bZWkcz3jXX0k6F2RXT6WtA Sup;
};
struct tyObject_TColormap_ffedPyHcMNOUVx9b7EeJOdA {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
int size;
tyObject_TColor_1uV5aNd07fYQ7fBdV9acKvg* colors;
tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg* visual;
void* windowing_data;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
typedef NU8 tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg;
struct tyObject_TFont_XHuvLWa6e1olxYK0w9c4IqQ {
tyEnum_TFontType_nhWPhgR9a7aI9ahmxS3NZHhg type_0;
int ascent;
int descent;
};
typedef NCSTRING tyArray_J70ZWTopZxz1yNsmbJgQug[5];
typedef NI32 tyArray_CWoQ39cMobP9audxQ5BU3NgA[5];
struct tyObject_TRcStyle_ITL4pVKqW9aRKG8wjXDBUcQ {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
NCSTRING name;
tyArray_J70ZWTopZxz1yNsmbJgQug bg_pixmap_name;
tyObject_TFontDescription_rUFGTm9aibpVXQoCzFvXTHw* font_desc;
tyArray_CWoQ39cMobP9audxQ5BU3NgA color_flags;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg fg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg bg;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg text;
tyArray_9chWiMwZsMCYI2hkwl9cKGsg base;
int xthickness;
int ythickness;
void* rc_properties;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* rc_style_lists;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* icon_factories;
NU16 RcStyle_flag0;
};
struct tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw {
void* data;
tyObject_TGSList_DeESIMA3HMF1yF7ekHec9cw* next;
};
struct tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ {
void* data;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* next;
tyObject_TGList_Wrm9b9bZ0tmo9c9c5gLvzYc5YQ* prev;
};
typedef NU8 tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ;
typedef NU8 tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ;
struct tyObject_TVisual_J4eHT2CRYoHA32q12s9ctYg {
  tyObject_TGObject_BTnUh4wiVhc6pyMxtnAgCg Sup;
tyEnum_TVisualType_TR8Ew8oq9b8acgpEx6OHNhQ TheType;
int depth;
tyEnum_TByteOrder_yshrw8HYFOH63IsYj7iZOQ byte_order;
int colormap_size;
int bits_per_rgb;
NU32 red_mask;
int red_shift;
int red_prec;
NU32 green_mask;
int green_shift;
int green_prec;
NU32 blue_mask;
int blue_shift;
int blue_prec;
tyObject_TScreen_lroEh79acPUUMJDTbxPzGDg* screen;
};
struct tySequence_jwzrUFjG9akTIJTBBFvvqxw {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nim_init_BI4x6i9c40Tf9b1BitVLexNw)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_jwzrUFjG9akTIJTBBFvvqxw)(void* p, NI op);
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_7)(void);
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_11)(void);
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_15)(void);
N_NIMCALL(NimStringDesc*, show_sl9blkPZ65KsAxetCsPgBmQ)(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA* di);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, checkExtensionOnSave_iwSvCNUKUzzQSQe1bblOnA)(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA* di, NimStringDesc** res);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
tySequence_jwzrUFjG9akTIJTBBFvvqxw* dialogFileOpenDefaultButtons_5mB6brIxBSsUuOGDZqd1QQ;
extern TNimType NTI_XOVT24GHXwqiEj5GCsEGCA_;
TNimType NTI_jwzrUFjG9akTIJTBBFvvqxw_;
tySequence_jwzrUFjG9akTIJTBBFvvqxw* dialogFileSaveDefaultButtons_eeW9cx9cwv4W2yB9caWykDe3w;
tySequence_jwzrUFjG9akTIJTBBFvvqxw* dialogFolderCreateDefaultButtons_I1ckc9bWx9b2QrNJvnRVeOmw;
tySequence_jwzrUFjG9akTIJTBBFvvqxw* dialogFolderSelectDefaultButtons_zER4bYuBRks9aiSwY9cr2dlQ;
extern tyProc_9bOzc7UlDODnFkXwgIFRMhQ Dl_180576_;
extern tyProc_cT6nc9bTXuu7BJHX4b3B2zw Dl_147922_;
extern tyProc_cdf3zj2SHJFUTOjrJqabGQ Dl_180864_;
extern tyProc_DozXQSyXdATJiFNw9cGbNUw Dl_180756_;
extern tyProc_hHzk7h6h9bFcD2HfWQwRJYg Dl_180769_;
extern tyProc_oibsqiXOm4p4sjxDY49aLkA Dl_180941_;
extern tyProc_fEK6vbvxQgPdAeHQUcvIEg Dl_147947_;
extern tyProc_RHLu5VhvToWoKn2DdN5gIg Dl_180840_;
extern tyProc_VoMKl77iPAbE7kH39bhiGLA Dl_144086_;
extern tyProc_BBveUfKT9b2ZY0NnHp9cisMg Dl_152613_;
extern tyProc_BBveUfKT9b2ZY0NnHp9cisMg Dl_152629_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_y10hFkY3rXXKk1LCL8ocQg_4, "Cancel", 6);
STRING_LITERAL(TM_y10hFkY3rXXKk1LCL8ocQg_5, "Open", 4);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[2];
} TM_y10hFkY3rXXKk1LCL8ocQg_6 = {{2, 2}, {{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_4),
((NI) -6)}
,
{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_5),
((NI) -3)}
}};
NIM_CONST tySequence_jwzrUFjG9akTIJTBBFvvqxw* TM_y10hFkY3rXXKk1LCL8ocQg_3 = ((tySequence_jwzrUFjG9akTIJTBBFvvqxw*)&TM_y10hFkY3rXXKk1LCL8ocQg_6);
STRING_LITERAL(TM_y10hFkY3rXXKk1LCL8ocQg_9, "Save", 4);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[2];
} TM_y10hFkY3rXXKk1LCL8ocQg_10 = {{2, 2}, {{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_4),
((NI) -6)}
,
{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_9),
((NI) -3)}
}};
NIM_CONST tySequence_jwzrUFjG9akTIJTBBFvvqxw* TM_y10hFkY3rXXKk1LCL8ocQg_8 = ((tySequence_jwzrUFjG9akTIJTBBFvvqxw*)&TM_y10hFkY3rXXKk1LCL8ocQg_10);
STRING_LITERAL(TM_y10hFkY3rXXKk1LCL8ocQg_13, "Create", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[2];
} TM_y10hFkY3rXXKk1LCL8ocQg_14 = {{2, 2}, {{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_4),
((NI) -6)}
,
{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_13),
((NI) -3)}
}};
NIM_CONST tySequence_jwzrUFjG9akTIJTBBFvvqxw* TM_y10hFkY3rXXKk1LCL8ocQg_12 = ((tySequence_jwzrUFjG9akTIJTBBFvvqxw*)&TM_y10hFkY3rXXKk1LCL8ocQg_14);
STRING_LITERAL(TM_y10hFkY3rXXKk1LCL8ocQg_17, "Select", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[2];
} TM_y10hFkY3rXXKk1LCL8ocQg_18 = {{2, 2}, {{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_4),
((NI) -6)}
,
{((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_17),
((NI) -3)}
}};
NIM_CONST tySequence_jwzrUFjG9akTIJTBBFvvqxw* TM_y10hFkY3rXXKk1LCL8ocQg_16 = ((tySequence_jwzrUFjG9akTIJTBBFvvqxw*)&TM_y10hFkY3rXXKk1LCL8ocQg_18);
STRING_LITERAL(TM_y10hFkY3rXXKk1LCL8ocQg_20, "len(a) == L seq modified while iterating over it", 48);
static N_NIMCALL(void, Marker_tySequence_jwzrUFjG9akTIJTBBFvvqxw)(void* p, NI op) {
	tySequence_jwzrUFjG9akTIJTBBFvvqxw* a;
	NI T1_;
	a = (tySequence_jwzrUFjG9akTIJTBBFvvqxw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	}
}
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_2)(void) {
	nimGCvisit((void*)dialogFileOpenDefaultButtons_5mB6brIxBSsUuOGDZqd1QQ, 0);
}
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_7)(void) {
	nimGCvisit((void*)dialogFileSaveDefaultButtons_eeW9cx9cwv4W2yB9caWykDe3w, 0);
}
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_11)(void) {
	nimGCvisit((void*)dialogFolderCreateDefaultButtons_I1ckc9bWx9b2QrNJvnRVeOmw, 0);
}
static N_NIMCALL(void, TM_y10hFkY3rXXKk1LCL8ocQg_15)(void) {
	nimGCvisit((void*)dialogFolderSelectDefaultButtons_zER4bYuBRks9aiSwY9cr2dlQ, 0);
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, show_sl9blkPZ65KsAxetCsPgBmQ)(tyTuple_pt9brTQdXTI4a3rvyv9bPLOA* di) {
	NimStringDesc* result;
	tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g action;
	tySequence_jwzrUFjG9akTIJTBBFvvqxw* defaultButtons;
	tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* dialog;
	tySequence_jwzrUFjG9akTIJTBBFvvqxw* buttons;
	int res;
	tyObject_TDialog_ebWAjsBELk37O6OlDglHLw* T38_;
	tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* T43_;
	nimfr_("show", "unix_dialog.nim");
	result = (NimStringDesc*)0;
	action = (tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g)0;
	defaultButtons = (tySequence_jwzrUFjG9akTIJTBBFvvqxw*)0;
	nimln_(34, "unix_dialog.nim");
	switch ((*di).Field0) {
	case ((tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg) 0):
	{
		nimln_(36, "unix_dialog.nim");
		action = ((tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g) 0);
		nimln_(37, "unix_dialog.nim");
		genericSeqAssign((&defaultButtons), dialogFileOpenDefaultButtons_5mB6brIxBSsUuOGDZqd1QQ, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	}
	break;
	case ((tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg) 1):
	{
		nimln_(39, "unix_dialog.nim");
		action = ((tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g) 1);
		nimln_(40, "unix_dialog.nim");
		genericSeqAssign((&defaultButtons), dialogFileSaveDefaultButtons_eeW9cx9cwv4W2yB9caWykDe3w, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	}
	break;
	case ((tyEnum_DialogKind_JFweU9bdIxrlcwAU16YwFQg) 2):
	{
		nimln_(42, "unix_dialog.nim");
		action = ((tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g) 2);
		nimln_(43, "unix_dialog.nim");
		genericSeqAssign((&defaultButtons), dialogFolderSelectDefaultButtons_zER4bYuBRks9aiSwY9cr2dlQ, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	}
	break;
	default:
	{
		nimln_(45, "unix_dialog.nim");
		action = ((tyEnum_TFileChooserAction_K0gq9aQKrx8TAtOdH1LAL3g) 3);
		nimln_(46, "unix_dialog.nim");
		genericSeqAssign((&defaultButtons), dialogFolderCreateDefaultButtons_I1ckc9bWx9b2QrNJvnRVeOmw, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	}
	break;
	}
	nimln_(48, "unix_dialog.nim");
	dialog = Dl_180576_((*di).Field1->data, NIM_NIL, action, NIM_NIL);
	nimln_(50, "unix_dialog.nim");
	genericSeqAssign((&buttons), (*di).Field5, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	nimln_(51, "unix_dialog.nim");
	{
		if (!(buttons == 0)) goto LA7_;
		nimln_(52, "unix_dialog.nim");
		genericSeqAssign((&buttons), defaultButtons, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	}
	LA7_: ;
	{
		tyTuple_XOVT24GHXwqiEj5GCsEGCA button;
		NI i;
		NI L;
		NI T10_;
		memset((void*)(&button), 0, sizeof(button));
		nimln_(3664, "system.nim");
		i = ((NI) 0);
		nimln_(3665, "system.nim");
		T10_ = (buttons ? buttons->Sup.len : 0);
		L = T10_;
		{
			nimln_(3666, "system.nim");
			while (1) {
				tyObject_TDialog_ebWAjsBELk37O6OlDglHLw* T13_;
				tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA* T14_;
				NI TM_y10hFkY3rXXKk1LCL8ocQg_19;
				if (!(i < L)) goto LA12;
				nimln_(3667, "system.nim");
				if ((NU)(i) >= (NU)(buttons->Sup.len)) raiseIndexError();
				button.Field0 = buttons->data[i].Field0;
				button.Field1 = buttons->data[i].Field1;
				nimln_(55, "unix_dialog.nim");
				T13_ = (tyObject_TDialog_ebWAjsBELk37O6OlDglHLw*)0;
				T13_ = &dialog->Sup;
				T14_ = (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*)0;
				T14_ = Dl_147922_(T13_, button.Field0->data, ((int)chckRange(button.Field1, ((int) (-2147483647 -1)), ((int) 2147483647))));
				T14_;
				nimln_(3668, "system.nim");
				TM_y10hFkY3rXXKk1LCL8ocQg_19 = addInt(i, ((NI) 1));
				i = (NI)(TM_y10hFkY3rXXKk1LCL8ocQg_19);
				nimln_(3669, "system.nim");
				{
					NI T17_;
					T17_ = (buttons ? buttons->Sup.len : 0);
					if (!!((T17_ == L))) goto LA18_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_20));
				}
				LA18_: ;
			} LA12: ;
		}
	}
	nimln_(57, "unix_dialog.nim");
	{
		int T24_;
		if (!(((NI) 0) < ((*di).Field3 ? (*di).Field3->Sup.len : 0))) goto LA22_;
		nimln_(58, "unix_dialog.nim");
		T24_ = (int)0;
		T24_ = Dl_180864_(dialog, (*di).Field3->data);
		T24_;
	}
	LA22_: ;
	nimln_(60, "unix_dialog.nim");
	{
		tyObject_TFileFilter_WygTTSr9cSqDmEH3XEJvTrQ* pfi;
		if (!!(((*di).Field2 == 0))) goto LA27_;
		nimln_(61, "unix_dialog.nim");
		pfi = Dl_180756_();
		{
			NimStringDesc* fi;
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
			NI i_2;
			NI L_2;
			NI T30_;
			fi = (NimStringDesc*)0;
			colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			nimln_(62, "unix_dialog.nim");
			colontmp_ = (*di).Field2;
			nimln_(3664, "system.nim");
			i_2 = ((NI) 0);
			nimln_(3665, "system.nim");
			T30_ = (colontmp_ ? colontmp_->Sup.len : 0);
			L_2 = T30_;
			{
				nimln_(3666, "system.nim");
				while (1) {
					NI TM_y10hFkY3rXXKk1LCL8ocQg_21;
					if (!(i_2 < L_2)) goto LA32;
					nimln_(3667, "system.nim");
					if ((NU)(i_2) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
					fi = colontmp_->data[i_2];
					nimln_(63, "unix_dialog.nim");
					Dl_180769_(pfi, fi->data);
					nimln_(3668, "system.nim");
					TM_y10hFkY3rXXKk1LCL8ocQg_21 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_y10hFkY3rXXKk1LCL8ocQg_21);
					nimln_(3669, "system.nim");
					{
						NI T35_;
						T35_ = (colontmp_ ? colontmp_->Sup.len : 0);
						if (!!((T35_ == L_2))) goto LA36_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_y10hFkY3rXXKk1LCL8ocQg_20));
					}
					LA36_: ;
				} LA32: ;
			}
		}
		nimln_(64, "unix_dialog.nim");
		Dl_180941_(dialog, pfi);
	}
	LA27_: ;
	nimln_(66, "unix_dialog.nim");
	T38_ = (tyObject_TDialog_ebWAjsBELk37O6OlDglHLw*)0;
	T38_ = &dialog->Sup;
	res = Dl_147947_(T38_);
	nimln_(68, "unix_dialog.nim");
	switch (res) {
	case ((NI32) -3):
	case ((NI32) -8):
	case ((NI32) -10):
	{
		tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA* fileChooser;
		NCSTRING T40_;
		nimln_(70, "unix_dialog.nim");
		fileChooser = ((tyObject_TFileChooser_x1scaA5uSzhuwBcAjZyuKA*) (((void*) (dialog))));
		nimln_(71, "unix_dialog.nim");
		T40_ = (NCSTRING)0;
		T40_ = Dl_180840_(fileChooser);
		result = cstrToNimstr(T40_);
		nimln_(72, "unix_dialog.nim");
		checkExtensionOnSave_iwSvCNUKUzzQSQe1bblOnA(di, (&result));
	}
	break;
	case ((NI32) -2):
	case ((NI32) -9):
	case ((int) -6):
	case ((NI32) -7):
	{
		nimln_(74, "unix_dialog.nim");
		result = copyString(NIM_NIL);
	}
	break;
	default:
	{
		nimln_(76, "unix_dialog.nim");
		result = copyString(NIM_NIL);
	}
	break;
	}
	nimln_(78, "unix_dialog.nim");
	T43_ = (tyObject_TWidget_dVyXpYzER8cMWhw9bnE7ttA*)0;
	T43_ = &dialog->Sup.Sup.Sup.Sup.Sup;
	Dl_144086_(T43_);
	{
		nimln_(79, "unix_dialog.nim");
		while (1) {
			int T46_;
			int T47_;
			T46_ = (int)0;
			T46_ = Dl_152613_();
			if (!(((NI32) 0) < T46_)) goto LA45;
			nimln_(80, "unix_dialog.nim");
			T47_ = (int)0;
			T47_ = Dl_152629_();
			T47_;
		} LA45: ;
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_unix_dialogInit000)(void) {
	nimfr_("unix_dialog", "unix_dialog.nim");
nimRegisterGlobalMarker(TM_y10hFkY3rXXKk1LCL8ocQg_2);
nimRegisterGlobalMarker(TM_y10hFkY3rXXKk1LCL8ocQg_7);
nimRegisterGlobalMarker(TM_y10hFkY3rXXKk1LCL8ocQg_11);
nimRegisterGlobalMarker(TM_y10hFkY3rXXKk1LCL8ocQg_15);
	nimln_(6, "unix_dialog.nim");
	nim_init_BI4x6i9c40Tf9b1BitVLexNw();
	nimln_(9, "unix_dialog.nim");
	genericSeqAssign((&dialogFileOpenDefaultButtons_5mB6brIxBSsUuOGDZqd1QQ), TM_y10hFkY3rXXKk1LCL8ocQg_3, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	nimln_(14, "unix_dialog.nim");
	genericSeqAssign((&dialogFileSaveDefaultButtons_eeW9cx9cwv4W2yB9caWykDe3w), TM_y10hFkY3rXXKk1LCL8ocQg_8, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	nimln_(19, "unix_dialog.nim");
	genericSeqAssign((&dialogFolderCreateDefaultButtons_I1ckc9bWx9b2QrNJvnRVeOmw), TM_y10hFkY3rXXKk1LCL8ocQg_12, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	nimln_(24, "unix_dialog.nim");
	genericSeqAssign((&dialogFolderSelectDefaultButtons_zER4bYuBRks9aiSwY9cr2dlQ), TM_y10hFkY3rXXKk1LCL8ocQg_16, (&NTI_jwzrUFjG9akTIJTBBFvvqxw_));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_unix_dialogDatInit000)(void) {
NTI_jwzrUFjG9akTIJTBBFvvqxw_.size = sizeof(tySequence_jwzrUFjG9akTIJTBBFvvqxw*);
NTI_jwzrUFjG9akTIJTBBFvvqxw_.kind = 24;
NTI_jwzrUFjG9akTIJTBBFvvqxw_.base = (&NTI_XOVT24GHXwqiEj5GCsEGCA_);
NTI_jwzrUFjG9akTIJTBBFvvqxw_.flags = 2;
NTI_jwzrUFjG9akTIJTBBFvvqxw_.marker = Marker_tySequence_jwzrUFjG9akTIJTBBFvvqxw;
}

